### ISSUE TITLE
[rush] Resolving dependencies when building

### ISSUE THREAD

**Issue by tet123** [microsoft/rushstack#1053]
We have:
- **Applications,** built with webpack and not published to our registry
- **Modules/Packages**, some are built with babel and some not built at all, but all are published to the registry

We have created a script module to facilitate build, test and start (see code below). The issues show up when modules try to resolve and they are not found.

package.json scripts

```
  "scripts": {
    "build": "node ./node_modules/@ourname/scripts/bin/scripts.js build",
    "test": "node ./node_modules/@ourname/scripts/bin/scripts.js test",
    "start": "node ./node_modules/@ourname/scripts/bin/scripts.js start"
  },
```

Simplified code and show the absolute paths.

```
const { spawnSync } = require('child_process');

		const result = spawnSync(
			'node',
			''C:\\git\\frontend\\src\\tools\\scripts\\tasks\\build'',
			{ stdio: 'inherit' }
		);
```

```
const { spawnSync } = require('child_process');
const commandDir = resolve(__dirname, '../../../node_modules/.bin');

const command = 'webpack-cli';
const commandArgs = { 
args: '--mode production --config C:\\git\\frontend\\src\\tools\\config\\project\\configs\\webpack.config.js', 
debug: false 
}

spawnSync(join(commandDir, `${command}.cmd`), commandArgs || [], {
		stdio: 'inherit',
		env: Object.assign(commandEnv, env)
});
```

When we do simple builds with babel it transpiles correctly, but as soon as we run anything that needs to be resolved, like tests with jest, we can't resolve react etc. When we run webpack all it's dependencies are not resolved, so we can't create a compiled bundle. We also use cosmos, but it's dependencies are not resolved.

Our monorepos scripts used to work when we had the node_modules folder in the root and used yarn workspaces, but I can't seem to figure out how to setup everything correctly.

**Comment by pgonzal** [comment]
1. Does the **package.json** for each project correctly list the dependencies that it calls `require()` for?  If not, then you may have some [phantom dependencies](https://rushjs.io/pages/advanced/phantom_deps/).  One simple way to test this is to run `rush scan` in the project folder, and compare the list to the dependencies declared in the **package.json** file in that folder.

2. Do your scripts correctly resolve their dependencies?  For example, paths such as `resolve(__dirname, '../../../node_modules/.bin')` are unlikely to work correctly, since they do not follow the NodeJS [module resolution standard](https://nodejs.org/api/modules.html#modules_all_together) but instead are making assumptions that packages were installed according to the NPM tool's particular directory layout.

3. Could you share a branch with a simplistic monorepo that reproduces the error you're encountering?  That would help us to give more specific advice.

In general, Rush expects each project in your monorepo to behave as a proper NPM package that declares and resolves its dependencies according to the rules. (In other words, packages behave like properly isolated components.)  This is true even for projects that do not actually get published to an NPM registry.  (Often the majority of packages will be like this -- they don't need to get published because they are consumed exclusively by other projects within the monorepo.  But the NPM formalism is still important for proper component isolation, incremental builds, and eventually sharding across VMs.)

**Comment by iclanton** [comment]
This issue is stale at this point, so closing it out.
