### ISSUE TITLE
[api-extractor] Best practices regarding namespaces in typescript API's

### ISSUE THREAD

**Issue by rudolf** [microsoft/rushstack#1171]
@octogonz I'm wondering if you could provide any general guidance/best practices/pitfalls to avoid in terms of structuring a public typescript API?

To make the API and types as useful and discoverable as possible, you want to expose all types at the top-level, but for a larger API, how do you prevent type name collisions? I can think of two approaches:

1. Break the API up into many small independent packages, like Angular does, i.e. `@angular/router` `@angular/common/http`.
2. Create namespaces or modules (e.g. `import * as HttpService from './http_service'`) to organize types in a hierarchy that's still easy to navigate/discover for consumers.

Since (2) would require fixing #1029 and it doesn't sound like this has come up a lot internally at Microsoft I'm wondering if there are other reasons to prefer (1) or other options I haven't thought of.

**Comment by octogonz** [comment]
JavaScript's (and therefore TypeScript's) "namespaces" are not very good compared other languages.  Let's compare with C# for example.  C# namespaces have properties like this:

- **If you import the namespace, you can refer to all its members without qualifiers.**  For example, in C# if I import `System.Windows.Controls` then I can now refer to `Button` and `Border` without having to type `System.Windows.Controls.Button`.

   **BUT IN TYPESCRIPT**:  If I do `import * as controls from ___;`, I can shorten the name to `controls.Button`.  But if I want to say `Button` I need to add another `import { Button } from ___;` for every single name that I need.  This creates a lot of import clutter, which is the #1 problem that namespaces were promising to solve for us.

- **The source code for the namespaced APIs can be split across many files.**  In fact, a C# namespace can span multiple DLLs.  It may be the case that `Button` and `Border` are loaded from two different DLLs, but my app doesn't care; I import the namespace once, and the .NET linker sorts that stuff out.

   **BUT IN TYPESCRIPT**:  As soon as you start trying to split namespaces across files, you run into a bunch of awkwardness.  Things don't want to merge. (Or two interfaces merge into one, because you didn't realize they had the same name.)   If you use import statements, sometimes your file sees only a subset of its namespace.  Life's better with ambient declarations (i.e. everything's global variable), but now you've lost the ability to load two versions of your library side-by-side.  And if your namespace tries to span two NPM packages ("DLLs")-- let's just say, don't do that.

- **A namespace is the place where a type lives.**  The short name might be `Button`, but behind the scenes the full name for this C# type is `System.Windows.Controls.Button`.  This official full name enables all sorts of handy reflection and other processing.

   **BUT IN TYPESCRIPT**:  The `Button` can be added to many different namespaces, and it doesn't necessarily have any official home.  From looking at the source file containing `Button` it may not be obvious at all which namespace it's in.  It can even belong to the same namespace twice.

- **A type doesn't need to qualify the names of other siblings in its namespace.**  For example, if you're in `System.Windows.Controls.Button`, you can can refer to `System.Windows.Controls.Border` as `Border` without even having to import `System.Windows.Controls`.

   **BUT IN TYPESCRIPT**:  This totally does not work if your namespace is split across files using `import * as namespace from`.  It kind of works (due to JavaScript closures) if all your code is in one huge file.

Most of the TypeScript libraries I've seen that successfully use namespaces tend to be describing an execution context rather than a general utility library.  For example, the [Office Add-ins API](https://docs.microsoft.com/en-us/javascript/api/office?view=office-js) is provided for scripts that get loaded into the Excel application.  It provides a bunch of namespaced APIs such as `Office.AddinCommands.Event` that all hang off of a (nesting) global variable `Office`.  Your script would never import two side-by-side versions of the `Office` library because Excel loads you, not vice-versa.  And it's nice that the Excel native hosting container doesn't need to get involved with module loaders such as AMD/CommonJS/whatever.  All its native APIs are stuck somewhere on that global variable, and the rest is up to your script.

Whereas if you're doing generalized TypeScript development, the more code you write, the more absolutely imperative it becomes to break your code base up into components/contracts that can be compiled/loaded piecemeal, and whose dependency relationships form an orderly unidirectional graph.  NPM packages are the way to untangle the rat's nest.  When Microsoft SharePoint was rewritten in TypeScript, the code base got split into literally hundreds of (internal) NPM packages.  This turned out to be a very good way to contain sprawl.  And if you run API Extractor on each NPM package, it's a good way for reviewers to keep an eye on the contracts that really matter, without drowning in details.  

But... this brings us to my final contention with TypeScript namespaces:  **NPM packages already ARE namespaces.**  The package name is already a unique name, and in TypeScript you have to write that name whenever you import anything from that package.  

So what use are namespaces if you're also using packages? It might be useful if you have massive NPM packages that export so many types, people get confused by all the jumble.  But this feels like an antipattern.  We try to keep our NPM packages small, so they can have a single entry point, which allows us to treat them as all-or-nothing bundles (which speeds up Webpack and facilitates dynamic loading at runtime).  Also we try to insist on giving "charters" to every NPM package.  The charter is a clearly-defined inclusion criteria that prevents it from turning into a Katamari Ball where people endlessly add stuff without thinking.  (For example, a good charter might be: "APIs for working with URLs", or "APIs for showing dialog boxes".  Whereas a vague/overly broad charter might be:  "Stuff made by Bob's team," or "component utilities" -- all sorts of stuff could be considered a "component utility".)

But this is just my own limited experience.  Maybe others could share some cases where TypesScript namespaces led to really awesome and modular API designs.  :-)

**Comment by octogonz** [comment]
BTW I should contrast regular namespaces with "shallow" namespaces, whose purpose is to organize variables and functions, like a "static class" in C#.  For example:

```ts
/**
 * Operations for working with strings that contain text.
 */
export namespace Text {
  /**
   * Returns the same thing as targetString.replace(searchValue, replaceValue), except that
   * all matches are replaced, rather than just the first match.
   */
  export function replaceAll(input: string, searchValue: string, replaceValue: string): string {
    ...
  }

  /**
   * Converts all newlines in the provided string to use Windows-style CRLF end of line characters.
   */
  export function convertToCrLf(input: string): string {
    ...
  }
  ...
}
```

I'm a strong supporter of this pattern, versus cluttering up the package exports with lots of loose variables and functions.  It has several benefits:  When you search/replace for `Text.replaceAll`, it's more accurate than searching for a short string like `replaceAll` (that may have tons of false matches).  And it forces people to think of a container name like `Text`, which in my opinion leads to APIs that are more readable and better organized, particularly when presented on a docs web site.  People sometimes point out performance issues ("tree shakers" won't break down shallow namespaces), but that seems like an engineering problem to solve, not an API design principle.

If you look our real [Text API](https://github.com/Microsoft/web-build-tools/blob/f41319f14d39f029ca4a419a2aba4c1d8cfbd2dc/libraries/node-core-library/src/Text.ts#L40) however, you'll find that it is actually a `class` and not a `namespace`.  Why do we do that?  Turns out that TypeScript static classes have some attractive features that namespaces seem to lack:

- Static classes can have property setters/getters; namespaces can't
- TypeScript static classes support inheritance.  You can use `super` to call base class members, which seems weird, but is actually pretty useful.  (Here's [an example](https://github.com/Microsoft/web-build-tools/blob/f41319f14d39f029ca4a419a2aba4c1d8cfbd2dc/apps/api-extractor-model/src/items/ApiDocumentedItem.ts#L37) from API Extractor itself.)
- Static classes can have private members.  Namespaces can simulate this using closures, but you can't inspect closure variables easily in a debugger.

The only real downside of using static classes is that the compiler emits a useless constructor body.  This annoys some purists, but I'm fine with it heheh.

**Comment by octogonz** [comment]
Closing due to lack of recent activity.
