### ISSUE TITLE
[rush] Generalize "review categories" into tags for project selection

### ISSUE THREAD

**Issue by bsiegel** [microsoft/rushstack#1241]
The concept of "categories" or groups of packages is fairly powerful, and has much use outside of just indicating which dependencies are approved for a given group of packages. For example, they could be used to name a group of packages to build on the command line, rather than passing `-t` multiple times. This is the specific situation I'm personally interested in (selecting a subset of packages to build) but I believe there are likely other uses as well.

Additionally, the way the term "category" is used in Rush today requires that a given package be assigned to just a single category. I propose that instead, we use "tags" - the terminology differs only in that tags are implied to be assignable to multiple packages, and that a package may likewise assigned to multiple tags. Set-based operations could then be performed on tagged packages, for example to select a union (packages with tags "production" or "internal"), an intersection (packages with tags "production" and "library"), or a difference (packages with the tag "production" but not "utility").

I propose modifying `rush.json` so that a package can have an array of `tags`.  This would be mutually exclusive with `reviewCategory` which can be kept for backwards compatibility and would be equivalent to `tags: ["myCategory"]`:

```
 "projects": [
    {
      "packageName": "application",
      "projectFolder": "application",
      "tags": ["production", "apps"]
    },
    {
      "packageName": "lib1",
      "projectFolder": "lib1",
      "tags": ["internal", "libs"]
    },
    {
      "packageName": "lib2",
      "projectFolder": "lib2",
      "tags": ["production", "libs"]
    }
  ]
```

I propose introducing the concept of a tag expression, which can be used to select packages by their tags:

A single tag: "production"
A union: "production,internal"
An intersection: "production,&library"
A difference: "production,-utility"

The syntax is totally up for debate, this is just to give an example.

I then propose modifying the behavior of commands which take a package specifier, such as `rush build -t <package>`. These commands would be modified to also accept a tag expression. I feel like simply allowing a tag expression to be used in place of a package name is a better alternative to introducing a new flag, but I'm open to opinions either way. If we do reuse the flag, it might be a good idea to have a prefix to distinguish a tag from just a package that happens to have the same name as a tag.

It might also be worth exploring allowing the user to configure a default tag specifier which would be applied to commands like `rush build`, so that for example, certain packages are excluded by default unless one of their tags is explicitly included.

**Comment by octogonz** [comment]
> This would be mutually exclusive with `reviewCategory` which can be kept for backwards compatibility and would be equivalent to `tags: ["myCategory"]`:

@bsiegel if we eliminate `reviewCategory`, then we should consider:

1. How do we indicate which tags should be treated as review categories?  We wouldn't want every random tag to get tracked in **browser-approved-packages.json**.  (See [here](https://rushjs.io/pages/maintainer/setup_policies/) for details.)

2. Today when `approvedPackagesPolicy` is enabled, every project must belong to a review category.  How would we enforce that?  Or if we don't enforce it, how does approval work for projects with no tags?

**Comment by octogonz** [comment]
>  I feel like simply allowing a tag expression to be used in place of a package name is a better alternative to introducing a new flag, but I'm open to opinions either way.

Agreed.

> If we do reuse the flag, it might be a good idea to have a prefix to distinguish a tag from just a package that happens to have the same name as a tag.

The natural prefix would be `#`, but the Bash will discard this.  Bash also applies special interpretation to many other symbol characters.

NPM package names can’t start with a dot or an underscore, and (in modern times) they never contain uppercase characters.

Here's some possible ideas (realizing that tags need a way to delimit multiple words):

```shell
# 1
$ rush build --to @my_tag

# 2
$ rush build --to MY_TAG

# 3
$ rush build --to MyTag

# 4
$ rush build --to _my_tag

# 5
$ rush build --to .my_tag

# 6
$ rush build --to +my_tag
```

#2 seems not too bad...

> A single tag: "production"
> A union: "production,internal"
> An intersection: "production,&library"
> A difference: "production,-utility"

I'm less sure about this feature.  It seems more esoteric, and the benefits may be outweighed by the costs of the additional command-line parsing complexity.  I wonder if the same problems could be solved by (1) allowing individual developers to define their own tags in a personal config file, and (2) allowing tag definitions to include other tags.

**Comment by bsiegel** [comment]
Huh, I definitely wrote up a response to this but must have never actually posted it.

For defining review categories, what if we just keep it exactly as it is today:

```
"approvedPackagesPolicy": {
  "reviewCategories": [ "published", "internal" ]
}
```

where the valid entries in the `reviewCategories` array are tag names? Does that avoid bloating the browser-approved-packages.json?

My initial instinct is that if any review categories are defined, we require all packages to be tagged with one of those category tags. That seems like it would stay closest to the existing implementation.

---

I think the idea of a personal config is a good replacement for the tag grammar I suggested. It should cover most or all of the scenarios and would keep things simple. Tags should definitely be able to include both projects and other tags in their definition.

The sigil question is tricky. "@" is too confusing to mix up with organizations. Using just capitalization violates the principle of least surprise for me. And finally I feel like it would be nice to avoid any characters that can be part of a package name, whether NPM allows them at the beginning or not, leading me to want to exclude "_" and ".". I sort of like "+" since it helps distinguish that it's a group of many packages. But perhaps `$ rush build --to :my_tag` ? The colon is easier to type than the plus, and I think my experience with Maven and Ansible both using colon in their command lines for (vaguely) related things makes my brain like this option the best so far.

**Comment by bsiegel** [comment]
After doing a little more thinking on this, I wonder what the tradeoffs of the following approach might be:

Consider a global flag such as `--limit <tag>` (or maybe `--context <tag>`). When specified, all it would do is change how Rush loads its set of projects. Normally, every project in the `projects` array is loaded. This flag would modify that logic to only discover projects which have the specified tag. The flag could be passed multiple times, expanding the scope of discovered projects.

Not sure what the implications of this would be with respect to discovering dependencies, and dependency version alignment, I need to think this through a bit more. But wanted to get this idea down somewhere that we could beat it up.

**Comment by RIP21** [comment]
@bsiegel interesting idea. Actually having as subset of pnpm-locks for faster  install for some certain tags would be nice.
I mean, like you have 100 modules and 30 SPAs that are hosted on different domains etc. Some of them are using only 6-7 shared modules, and rest of the 70 are useless for them until they are use them.
So instead of full install having an optimised install for particular app would be awesome thing. Surely `ensureConsistentVersions` should still be in force for those subsets as well as other stuff.
Sounds like it's too much responsibility for Rush, but really, that would be awesome to have for REALLY big monorepos that may have also Node backends, frontends, libs and all that mixed stuff. At least for quicker CI installs, locally it's not a big deal as pnpm is quick and `ensureConsistentVersions` helps a lot, but you know, just thoughts to the air.
@octogonz what do you think?

**Comment by octogonz** [comment]
> Consider a global flag such as `--limit <tag>` (or maybe `--context <tag>`). When specified, all it would do is change how Rush loads its set of projects. Normally, every project in the `projects` array is loaded. This flag would modify that logic to only discover projects which have the specified tag. The flag could be passed multiple times, expanding the scope of discovered projects.
> 
> Not sure what the implications of this would be with respect to discovering dependencies, and dependency version alignment, I need to think this through a bit more. 

I think it would work fine as long as Rush automatically expands the scope to include any dependency projects.

For example, suppose project `A` depends on `B`, and `B` depends on `C`.  If I is selected via a tag, then `B` and `C` should also be selected.  Otherwise commands like `rush install` or `rush build` would not work properly.

**Comment by octogonz** [comment]
> So instead of full install having an optimised install for particular app would be an awesome thing. 

With PNPM and `useWorkspaces=true`, you can now do `rush install --to my-project` to only install the subset of dependencies needed to build `my-project`.  (It's apparently been around for a while, but I just found out about it today. 😁)

So it would be natural to generalize this to work with tags.

> Sounds like it's too much responsibility for Rush, but really, that would be awesome to have that for REALLY big monorepos that may have also Node backends, frontends, libs and all that mixed stuff. 

I don't think it's too much responsibility.  Rush's entire focus is on large scale scenarios and their complexities.  I think we'd absolutely consider supporting something like this.  To get it off the ground, we'd need someone to create a GitHub issue that presents a concrete example of a monorepo setup that would motivate this feature, along with a proposed design for how it would be implemented, and how it would interact with Rush's other features.

**Comment by octogonz** [comment]
This "project tags" feature looks relatively easy to implement, so let's see if we can reach a consensus for its design.

### What does a tag name look like?

Looks like I was favoring `MY_TAG` because it's simple and readable, while also being forbidden as an NPM package name. @bsiegel proposed `+my_tag` or `:my_tag`, to avoid uppercase letters.

>  I think my experience with Maven and Ansible both using colon in their command lines for (vaguely) related things makes my brain like this option the best so far.

Seems like Maven and Ansible both use colons as a separator (similar to `npm run build:docs` rather than as a prefix).

>  I sort of like "+" since it helps distinguish that it's a group of many packages.

I also like that `+` resembles the letter "t" for tag.  Any objections to `+my_tag`?

### Are the names case-sensitive?

Since tags are typed on a command line (and may later be specified in user-specific configs), I think it would be highly confusing for `#This` and `#this` to refer to different things.

It might be simplest to enforce tags must be entirely lowercase:

```js
// Valid tags:
//   +_
//   +abc_123
//   +_multi_word_tag
//   +multiwordtag
//
// Not allowed:
//  +
//  +123
//  +MultiWordTag
//  +MULTI_WORD_TAG
//  +interñătional
const validTagName: RegExp = /^\+[a-z_][a-z_0-9]*$/;
```

### How are tags defined?

I'm fine with this proposal:
```js
 "projects": [
    {
      "packageName": "my-app",
      "projectFolder": "my-app",
      "tags": ["+apps", "+multi_word_tag"]
    },
```

We could later supplement it with user-defined tags.

### How do tags relate to review categories?

Currently review categories are defined like this:
```js
"approvedPackagesPolicy": {
  "reviewCategories": [ "public", "internal" ]
}
```
...and used like this:
```js
 "projects": [
    {
      "packageName": "my-app",
      "projectFolder": "my-app",
      "tags": ["+apps", "+multi_word_tag"],
      "reviewCategory": "internal"
    },
}
```

Seems like there's a couple options:

1. Review categories have no relationship to tags.  You'd need to manually add `"tags": ["+apps", "+multi_word_tag", "+internal"],` if you want a tag with the same name.
2. Review categories are also tags.  To avoid case-sensitivity and other ambiguities, I feel like this would require us to impose a restriction that _**review category names must conform to the tag syntax.**_  Otherwise the design is too confusing.  This would be a breaking change, since currently the category naming is very permissive.

After some thought, I think I'm strongly in favor of #1. Looking at how we use review categories in practice, they are not meaningful selectors for `rush build` or `rush install`.

### What operators are supported?

> I propose introducing the concept of a tag expression, which can be used to select packages by their tags:
> 
> A single tag: "production"
> A union: "production,internal"
> An intersection: "production,&library"
> A difference: "production,-utility"

Let's skip this for now. It seems like overengineering.  Let's release a basic tagging feature and get experience using it in real world monorepos. Then if we encounter pain points with those limitations, we'll have a better idea how to design this.

(BTW my own intuition is that expressions like `rush build --to +production,&-+library` will be too confusing. How can a regular person envision what's getting selected by that?  Maybe instead we could provide a way to make personal tags, and some bulk commands for tagging/untagging projects. So the workflow is three steps: (1) tag the things you're interested in, (2) review the set of projects your tag applies to, (3) use the tag with a simple syntax like `rush build --to +my_tag`.)

### How does the "context" concept work?

> Consider a global flag such as `--limit <tag>` (or maybe `--context <tag>`). When specified, all it would do is change how Rush loads its set of projects. Normally, every project in the `projects` array is loaded. This flag would modify that logic to only discover projects which have the specified tag. The flag could be passed multiple times, expanding the scope of discovered projects.

This is a great idea.  But let's skip it as well. It will be easier to design after the basic feature is shipped.

**Comment by octogonz** [comment]
Any objections/additions/feedback regarding the note above?  If not, I think it's a complete enough design that someone could make a PR.

**Comment by RIP21** [comment]
Love everything so far. Just unsure if + is good prefix :) Everywhere hash
is a prefix for tags (or a for a hashtags? :D)

But other than that, would be awesome to see it shipped to get some hands
on experience on it and iterate on it as soon as possible :)

**Comment by bsiegel** [comment]
I'm on board with the proposal. I understand that using a #hashtag would feel natural, but unfortunately shells interpret that as the beginning of a comment.

I would propose that tags are defined without the sigil as it feels more natural to the user, e.g.
```json
 "projects": [
    {
      "packageName": "my-app",
      "projectFolder": "my-app",
      "tags": ["apps", "my_favorite_service"]
    },
```

But when using or referring to a tag, the user would prefix them with the `+` sigil to indicate they intend to refer to a tag and not a named package. I would also suggest that hyphens be allowed in the tag name, I don't see any specific reason for disallowing them.

So if we were to add tagging as described in the design document above, and leave the "context" concept for another day, what would be the utility of the tags? How would a user interact with them once defined, or in what operations would tags be useful?

**Comment by octogonz** [comment]
In a recent [chat thread](https://rushstack.zulipchat.com/#narrow/stream/262513-general/topic/Dependency.20policies/near/247170221), @Alber70g pointed out that the `nx.dev` build system also implements tags for projects, configured using [this  setting](https://nx.dev/latest/react/structure/monorepo-tags#tags).  However they seem to be primarily used to specify build dependency relationships (e.g. `"depConstraints"` and `"onlyDependOnLibsWithTags"`) rather than project selection.

**Comment by octogonz** [comment]
I've clarified the issue titles:

- #1241 tracks the proposal to use Rush project tags as project selectors (`rush build --to +my-tag`)
- #2831 tracks the proposal to use Rush project tags for dependency policies.

**Comment by dmichon-msft** [comment]
I personally favor:
`rush build -t tag:apps`
which then allows similarly:
`rush build -t policy:some-version-policy`
And the removal of `--to-version-policy` as a special case. Also makes the context really obvious at the expense of a few characters. In the event that we want other categories of projects in the future, we can do so without adding any more command line options. For example, if we want to support:
`rush build -t scope:@rushstack`

**Comment by RIP21** [comment]
Just wondering if this is ever going to be implemented? :) --to and --from and many other variants of these are already good, but to make it 100% perfect tags would make so much sense. I'm still happy with Rush :) But just heads-up :)

**Comment by NickDarvey** [comment]
@RIP21 
>So instead of full install having an optimised install for particular app would be an awesome thing. Surely ensureConsistentVersions should still be in force for those subsets as well as other stuff.

Looks like PNPM is exploring this. See 'version groups' in https://github.com/pnpm/pnpm/discussions/4483.

**Comment by RIP21** [comment]
@NickDarvey it's already working :) With rush install -t and other flags that specify stuff.

**Comment by buffcode** [comment]
As the idea of union/intersection/difference was not implemented in this issue, I'm referencing https://github.com/microsoft/rushstack/issues/3327
