### ISSUE TITLE
[rush] Fail the build on stderr output

### ISSUE THREAD

**Issue by gregjacobs** [microsoft/rushstack#1259]
When a package's build prints output to stderr, the build "succeeds but with warnings." However, the build isn't actually considered successful since a `package-deps.json` file is not generated.

I'd like to avoid problems like this which prevents incremental builds by simply erroring out the build if anything is printed to stderr. This would make sure that developers aren't ignoring warnings as well.

Could an option be added to perhaps `rush.json` to enable this "error on warnings" functionality? Seems like it would be fairly straightforward to implement. Maybe can call it something like `treatWarningsAsErrors` or `errorOnStderr`?

**Comment by octogonz** [comment]
The current behavior is based around three user experiences:

1. **Warnings should fail a production build.**  A PR build should fail if any warnings were printed. This ensures that the master branch always builds with 0 warnings.  If warning cannot be addressed immediately, it should be suppressed rather than ignored. (In an active repo, ignoring warnings quickly leads to a situation where so warnings accumulate that nobody reads them any more, defeating the purpose of warnings.)

2. **Warnings should not interfere with local development.**  When you're working on a new feature and the code is half-baked, you don't care about warnings, and don't want to be forced to fix them. Thus `rush build` shouldn't build 5 projects and then fail to build the remaining 5 because of some warnings.

3. **Errors should break the build for any depedencies.**  If a project has a legitimate error, then `rush build` should not try to build other projects that depend on it.  This wastes time, since most likely those projects will fail to build also.

Today these behaviors are accomplished with the following rules:

- If a project's build process returns a nonzero, Rush interprets it as an error, and doesn't build dependent projects.  (Rush's process returns a nonzero exit code also.)
- If the build writes to stderr but returns a zero exit code, Rush interprets it as a warning, and continues building everything. But Rush itself returns a nonzero exit code, which ensures the CI job fails.

The feature you're asking for makes sense. It seems like a general enhancement that everyone would want, not an "opt in" behavior.  But your proposal seems like it would interfere with the goals mentioned above. I think it needs a different design.

Maybe the incremental build can somehow remember that a project built with warnings.  In a build that had warnings (but not errors), I think what we wants is for  `rush build` to finish instantly without rebuilding anything, but remember somehow that warnings happened, so it can return a nonzero exit code.

Maybe we need to add a field to `package-deps.json` to track whether there were warnings or not?

**Comment by gregjacobs** [comment]
Hey @octogonz, thanks for the response. You mentioned in ⋕1 that warnings should fail a production build, but they don't currently do so (at least not on our CI build). Is there a flag for `rush build` that enables that? I don't currently see any in: https://rushjs.io/pages/commands/rush_build/

I would actually be okay with just having our CI builds fail when a package emits warnings rather than to change the developer experience. But our project currently has two packages that emit warnings and rush returns a 0 exit code when running `rush build`

**Comment by octogonz** [comment]
What CI system are you using?

**Comment by gregjacobs** [comment]
GitLab. Our build fails when an individual package's build returns a non-zero exit code, but not when it simply emits to stderr.

Is there supposed to be a flag to enable this exit-with-non-zero code on warnings? I just noticed that the description of `rush build` talks about a `--production` flag, but it's not listed in the options output.

**Comment by octogonz** [comment]
I believe the Rush process itself should return a nonzero exit code, which is what causes the CI build to fail.  The `--production ` flag is not part of Rush. It's something that your build scripts may choose to implement, and then would get declared as a custom parameter for Rush's command line.

**Comment by gregjacobs** [comment]
I definitely agree: the rush process should return a nonzero exit code in this case, but unfortunately it seems it doesn't.

I just created a new project with a single package, whose `package.json` looks like this:

```json
{
    "name": "my-app",
    "scripts": {
        "build": "echo hello-stderr 1>&2"
    }
}
```

And then running `rush build`: 

```
~/dev/rush-test $ rush build


Rush Multi-Project Build Tool 5.7.1 - https://rushjs.io


Starting "rush build"

Executing a maximum of 8 simultaneous processes...

[my-app] started
hello-stderr
1 of 1: [my-app] completed with warnings in 0.01 seconds

SUCCESS WITH WARNINGS (1)
================================
my-app (0.01 seconds)
hello-stderr
================================


rush build (0.02 seconds)
(17:39:56) ~/dev/rush-test $ echo $?
0
```

I think if this was fixed, that would satisfy the 3 user experiences you mentioned above, as well as solve my use case in that I don't want CI builds to succeed if warnings are emitted :)

**Comment by octogonz** [comment]
Hrmmm... Ok. We'll investigate this. Thanks for providing repro instructions.

**Comment by gregjacobs** [comment]
Awesome, thanks!

**Comment by btilford** [comment]
Doesn't this break if your package is lets say a logger and you have tests that write to stderr?

**Comment by gregjacobs** [comment]
@btilford You could always capture the output of your tests or redirect it to sdtout. But actually this issue was fixed a little while ago so closing
