### ISSUE TITLE
[api-extractor] Problems with React global variable

### ISSUE THREAD

**Issue by natalieethell** [microsoft/rushstack#1324]
We were getting the following TSDoc warning when running api-extractor on our project, [office-ui-fabric-react](https://github.com/OfficeDev/office-ui-fabric-react). 

**@uifabric/utilities (1 minute 0.2 seconds)
Warning: C:/Users/naethell/office-ui-fabric-react/common/temp/node_modules/.registry.npmjs.org/@types/react/16.3.16/node_modules/@types/react/index.d.ts:724:8 - (tsdoc-characters-after-block-tag) The token "@deprecated" looks like a TSDoc tag but contains an invalid character "."; if it is not a tag, use a backslash to escape the "@"**

This is a warning coming from parsing a file in `@types/react`, not a file in our project - when api-extractor analyzes the React global variable, it doesn't realize that it's from an external library. It believes it's part of the local project, and tries to parse the TSDoc comments.

We got rid of the warning by adding `import * as React from 'react'` in all the files that were using the React variable but missing the import statement.

**Comment by octogonz** [comment]
Thanks for reporting this!  When I debugged it, it appears that the `ExportAnalyzer` follows the global into **@types/react/index.d.ts** without realizing that it has left the current project. Thus [AstSymbol.isExternal](https://github.com/microsoft/web-build-tools/blob/a31d421de8d52f6fd2c944a7de1ee3a9bc09aa66/apps/api-extractor/src/analyzer/AstSymbol.ts#L71) ends up being false, which is why the TSDoc comment is being parsed.

It's relatively uncommon for a public API to reference a type from global variable (in modern code, at least), but we should definitely fix this.  The resulting error message is pretty confusing.

**Comment by octogonz** [comment]
This came up again in https://github.com/microsoft/rushstack/issues/1765.  I'm going to close this issue, because the other investigation has progressed further.
