### ISSUE TITLE
[api-extractor] Provide a way to configure newlines in output files

### ISSUE THREAD

**Issue by levahim** [microsoft/rushstack#1366]
Both API Extractor and API Documenter have force CrLf line endings in all of the generated files. This creates troubles in development environments where usage of Lf line endings is enforced, especially when it is done automatically in editor configuration and git attributes. The CrLf endings appear to be hardcoded in the tools' logic. This needs to be configurable (e.g. in api-extractor.json config files).

**Comment by octogonz** [comment]
> This needs to be configurable (e.g. in api-extractor.json config files)

This topic applies to all the **web-build-tools** projects.

The choice tends to apply to an entire Git repo.  It would be annoying to have to configure each tool independently.  We could detect it based on the OS; however, we want deterministic builds.  When we tried the magic policy of *"Mac people get LF, Windows people get CRLF", then it sometimes caused OS-specific failures, which was bad.

In our repos, the policy is controlled by **.gitattributes** (see [this example](https://github.com/microsoft/web-build-tools/blob/2c941e21777393c67979b25dc087433485b12575/.gitattributes#L2)), which normalizes everything during commit.

Rather than having a config file setting, what if we based it on the line endings used in the _config file itself_?  Pretty much all of our tools start by reading a config file.  So we could take an approach of determining that file's line endings, and then using that convention for all the tool's output.

**Comment by octogonz** [comment]
BTW we originally standardized on CRLF because it's displayed correctly by nearly all editors.  Whereas on Windows, Notepad.exe and cmd.exe did not display LF correctly.

Technically LF is superior because it's simpler, though.  Today Windows 10 seems to support LF just fine even in Notepad.exe and cmd.exe.  We could also consider changing our default to LF.

**Comment by octogonz** [comment]
The [TypeScript compiler](https://www.typescriptlang.org/docs/handbook/compiler-options.html) has a `--newline` option.  We could copy that.

**Comment by levahim** [comment]
A few initial thoughts on the topic:

I'd say a config option is still the best approach. There are plenty other options already in all the config files, so adding one more won't add much to the annoyance.

The problem with .gitattributes is that it normalizes the files in other repos but leaves the local files with the original endings, which sometimes may lead to issues comparing the versions (for the generated files that are checked in, and for build files that are never checked in, but published).

Autodetection based on the file author's development env is probably not a good idea--developers use different platforms within one project. Non-deterministic builds and mixed endings in different files are problems.

One thought on kind of an autodetection is to look at some other commonly used configs that determine the endings, such as the same .gitattributes or even better .edtiroconfig. Feels a little clunky though to look into other tools' config files (.editorconfig, however, is not for any specific tool, so could be a good candidate). But an option in the tools' own config files still be needed to be able to explicitly set it for the project.

**Comment by octogonz** [comment]
Fair enough. Let's just make it a config option then. For API Documenter it would need to be a command-line parameter initially, as its config file is still in an experimental state.

**Comment by Beretta1979** [comment]
Hi I would like to contribute and take op this task. However, I do not find any information of how to start this. The link https://github.com/microsoft/rushstack/wiki/Contributing-to-this-repo seems to be dead. How do I continue?

**Comment by octogonz** [comment]
That document was moved here: https://rushstack.io/pages/contributing/get_started/

Where was the broken link?

**Comment by Beretta1979** [comment]
> That document was moved here: https://rushstack.io/pages/contributing/get_started/
> 
> Where was the broken link?

https://rushjs.io/pages/contributing/

**Comment by Beretta1979** [comment]
Can you give a hint about where this config option should reside and a good name for it?

**Comment by levahim** [comment]
> Can you give a hint about where this config option should reside and a good name for it?

I'd say it should be something similar to tsc's --newLine option.

**Comment by octogonz** [comment]
@iclanton I seem to remember at one point considering to switch to LF everywhere without any option. But I can't find the thread. Am I misremembering that?

**Comment by Beretta1979** [comment]
My PR would be to change it everywhere indeed (also for the rush files). But configurable is fine for me.

**Comment by octogonz** [comment]
Could you do a quick search of GitHub to see if anyone is actually using `tsc`'s newline option? If it's commonly used, then I think AE would be expected to support this at least for the .d.ts rollups.

**Comment by Beretta1979** [comment]
People seem to use it ...

**Comment by octogonz** [comment]
Ok. To speed this up, lemme create a branch that sets up the config settings for you, and then you can fill in the rest.

**Comment by octogonz** [comment]
@Beretta1979 Here's a branch that sets up the config file settings for API Extractor and API Documenter: [octogonz/issue1366](https://github.com/microsoft/rushstack/compare/b5f00a5314fbc0235c41e6aa16cc5c0067ca794d...octogonz/issue1366)

In order to use the experimental **api-documenter.json** config file, you need to use the `api-documenter generate` CLI instead of `api-documenter markdown`.  Note that **api-documenter.json** doesn't go through any normalization yet; we're planning to add that later after more settings are added.

Going forward, our philosophy for linefeeds will be:
- All tools should produce deterministic output regardless of operating system (we're deprecating reliance on NodeJS's `os.EOL`)
- Internal data structures (e.g. string variables) should always should use `\n` everywhere.
- For a CRLF output, the conversion should not be performed until the last possible step before writing the output.  The recommended APIs are [FileSystem.writeFile()](https://rushstack.io/pages/api/node-core-library.filesystem.writefile/) (which supports [IFileSystemWriteFileOptions.convertLineEndings](https://rushstack.io/pages/api/node-core-library.ifilesystemwritefileoptions.convertlineendings/)) or [Text.convertToCrLf()](https://rushstack.io/pages/api/node-core-library.text.converttocrlf/).

For your initial PR, I'd suggest to focus on API Extractor's output files, and not worry about other aspects such as the console output.

When you run [rush change](https://rushjs.io/pages/developer/everyday_commands/#rush-change), specify a MINOR SemVer bump.  I'm not too worried about "breaking" people by changing the default.

**Comment by Beretta1979** [comment]
Great, I will probably continue this during the weekend ...

**Comment by Beretta1979** [comment]
Forget about the PR I opened, this was done before I read the last comments you posted

**Comment by ecraig12345** [comment]
I took a stab at this in #1626. My approach is a bit different than the one in Pete's branch since I actually started my change several months ago, but I'll take a look at that branch now and update mine.

**Comment by ecraig12345** [comment]
My branch also doesn't cover api-documentor, but I could add that if desired.

**Comment by ecraig12345** [comment]
Another question from looking at the branch: currently the generated files are written with CRLF by default, but Pete's branch switches that to LF by default. While LF is probably more common in the open source community in general, it seems odd to change the default.

**Comment by ecraig12345** [comment]
Added API Documenter to the PR but kept the CRLF default pending further discussion.

**Comment by octogonz** [comment]
> My branch also doesn't cover api-documentor, but I could add that if desired.

This is less important, because the `api-documenter` outputs typically are not diffed or tracked by Git.  In the previous discussion, our overall decision was:

- Generally default all tooling output to use `\n`
- But provide a configuration to enable `\r\n` in specific situations where people care about it.

When we asked about API Extractor, people pushed back and said it should have an option for `\r\n` to maintain parity with the TypeScript compiler's `--newLine` option, since API Extractor generates .d.ts files.

**Comment by octogonz** [comment]
> While LF is probably more common in the open source community in general, it seems odd to change the default.

I'd be okay with waiting until the next major version to change the default.  Or at least postponing it until after a PR that updates all our other tooling to output `\n` by default.

**Comment by ecraig12345** [comment]
I think changing the default line endings all at the same time would make more sense than changing the API files now and other files later.

**Comment by levahim** [comment]
* Files generated by the API documenter absolutely do get checked in to git repos and get diffed.
* The default newline should probably be the same as that of `tsc`, for consistency reasons.

**Comment by octogonz** [comment]
@ecraig12345's fix was published  with API Extractor 7.6.0
