### ISSUE TITLE
[rush] Simplify setting allowWarningsInSuccessfulBuild for build and rebuild commands

### ISSUE THREAD

**Issue by mikeharder** [microsoft/rushstack#1375]
Please add a simpler method to set `allowWarningsInSuccessfulBuild` for the `build` and `rebuild` commands, without duplicating the commands in `command-line.json`.  More details:

https://github.com/microsoft/web-build-tools/issues/1329#issuecomment-502940264

**Comment by octogonz** [comment]
When `build` or `rebuild` is specified `command-line.json`, any omitted settings should default to the build-in settings as defined by [_addDefaultBuildActions()](https://github.com/microsoft/web-build-tools/blob/d5c1756c805f2f9a231fc648c9d50ae142c7abe9/apps/rush-lib/src/cli/RushCommandLineParser.ts#L176).  Since we're just merging settings from two objects, this should be pretty easy to implement.
