### ISSUE TITLE
[rush] Documentation for VSCode Remote setup

### ISSUE THREAD

**Issue by baflo** [microsoft/rushstack#1472]
**Is this a feature or a bug?**

- [x] Feature
- [ ] Bug

**Please describe the actual behavior.**

Do you have special recommendation how to use a rush repository in VSCode Remote Development?

At least on my Windows system, with my repository mounted from the host machine into a Linux container in VSCode remote dev the installation is very slow.

**What is the expected behavior?**

An installation speed at least similar to host.

* **Tool:** Rush
* **Tool Version:** 5.11.1 
* **Node Version:** 10.16.2 LTS
* **OS:** Windows 10 (1903)/Docker for Windows/VSCode Remote Dev

**Comment by iclanton** [comment]
I've never actually used this feature. Can you link to some docs on how to do this in VSCode?

**Comment by bbenoist** [comment]
@iclanton https://code.visualstudio.com/docs/remote/remote-overview

**Comment by octogonz** [comment]
This looks like a really cool feature!  I wonder if it provides security benefits, since all the code and build tools can run in an isolated environment (rather than on the developer's laptop with all their security keys).

@bbenoist Could you clarify why you believe this problem is specific to Rush?  Are other non-Rush repos faster?  Is there something about the Rush repo that seems to be slowing it down?  Maybe take a look at the [VS Code logs](https://github.com/Microsoft/vscode-go/wiki/Go-with-VS-Code-FAQ-and-Troubleshooting).

**Comment by bbenoist** [comment]
@octogonz I think that you've mentioned the wrong person. It's @baflo who opened the issue :wink:

As I understand it, @baflo's speed problem is not due to Rush but because his environment runs in a virtual machine (Docker for Windows is not native if the container is Linux).  
I would suggest @baflo to try [Windows Subsystem for Linux](https://docs.microsoft.com/windows/wsl) which is lighter since it's supposed to work directly with the Windows kernel instead of running an additional boot2docker Linux VM.

**Comment by octogonz** [comment]
I'm going to close this issue because it is not specific to Rush.

We would accept this documentation however as part of the https://rushstack.io/ guidance.  However, since the Rush maintainers haven't used this feature, we aren't in a good position to write the docs.

If someone wants to write up a draft of some instructions  that you think other Rush developers would benefit from, feel free to post it as an issue or PR for the https://github.com/microsoft/rushstack.io-website project.  Thanks!
