### ISSUE TITLE
[rush] Allow setting ensureConsistentVersions to false for specific projects only

### ISSUE THREAD

**Issue by crhayes** [microsoft/rushstack#1495]
**Is this a feature or a bug?**

- [x] Feature
- [ ] Bug

**Please describe the actual behavior.**

Currently, setting `ensureConsistentVersions: false` stops enforcing consistent versions for all projects.

**What is the desired behavior?**

Rather than turning the `ensureConsistentVersions` behaviour off for all projects, it would be nice to provide a set of projects to opt out of this behaviour, while allowing other projects to continue to enforce consistent versions.

A little context behind this request:

We currently have several projects, one of which is going into a code freeze. We would like to pin the dependency versions for this project, but allow all other projects to continue upgrading dependencies; however, we'd like to ensure these packages continue to use consistent package versions.

**Comment by iclanton** [comment]
You can approximate this by including the dependencies in your frozen projects in the `"allowedAlternativeVersions"` property of `common-versions.json`. See docs here: https://rushjs.io/pages/configs/common_versions_json/

Will that do what you're looking for? It's not exactly the same thing, but it might work for your scenario.

**Comment by crhayes** [comment]
@iclanton Thanks for the quick response! I came across that option in the documentation and had the same thoughts initially.

My understanding is that once a dependency is added to `allowedAlternativeVersions`, each project can specify any version of the dependency it likes (i.e. it essentially becomes the same as `ensureConsistentVersions: false` for that single dependency).

Because we want to freeze all dependencies in a single project over a long period of time, the list of `allowedAlternativeVersions` will grow over time as dependencies are upgraded. Theoretically every dependency we have could end up in this list, essentially making it the same as `ensureConsistentVersions: false`.

Please let me know if I've misunderstood how `allowedAlternativeVersions` works!

I should also note that we hardcode our dependencies to an exact version (no ranges). As an alternative, is it possible to specify two versions of a dependency under `allowedAlternativeVersions` rather than a range? This would allow us to peg one version for the frozen project, and one version for all others.

**Comment by elliot-nelson** [comment]
The `allowedAlternativeVersions` setting allows you to list multiple version(s) or version range(s) for each package that are allowed _in addition to the version all your other packages use_.

So for example, let's say today your entire monorepo is consistently using `react: ~17.4.0`. And then, you go and upgrade your entire repo _except one project_ to `react: ~18.0.5`.

This gives you an error, because you've enabled `ensureConsistentVersions`, so you add `"react": ["~17.4.0"]` to the `allowedAlternativeVersions` list, which allows your legacy project to continue using that version. If desired, you could instead specify a pegged version `17.4.0` and have your legacy project specify `17.4.0`, to make the allowed alternative versions list even stricter.

Rinse and repeat for each dependency that ends up locked in your legacy project.
