### ISSUE TITLE
[api-documenter] render remarks on top of the page

### ISSUE THREAD

**Issue by giniedp** [microsoft/rushstack#1550]
The markdown documenter renders the remarks at the bottom of the page. Is this a design decision? I'd prefer to have the remarks after the summary and before the member sections. If this is by design, can we have an option or a pluggable mechanism to change the rendering order?

**Comment by octogonz** [comment]
It's by design.  But we've been working on an **api-documenter.json** config file that will enable these sorts of customizations.

**Comment by octogonz** [comment]
@giniedp I assume that you're asking for remarks to appear before the "members" tables, such as on the page for an `interface` or `namespace`.  ([Example](https://rushstack.io/pages/api/node-core-library.filesystem/))

Or are you also wanting the remarks to appear above the "parameters" table for a function?  ([Example](https://rushstack.io/pages/api/node-core-library.executable.spawnsync/))

To me it seems like it would not appear before "parameters", because that table is relatively small.  Whereas class/interface/namespace/package members can be potentially large lists.

**Comment by giniedp** [comment]
yes, exactly. [like here](https://docs.microsoft.com/en-us/javascript/api/sp-core-library?view=sp-typescript-latest)
For methods and functions etc. its ok to place the remarks after the parameters where the table is small, and does not push the remarks out of sight.

**Comment by octogonz** [comment]
@giniedp Thinking about this more, what you're proposing seems to be a better design than the current behavior (which was modeled after DocFX, which I believed used to do it this way).  Maybe we should simply change it.  I'm not sure we need to make it configurable.

Are you able to create a PR?

**Comment by giniedp** [comment]
i'll look into it in the next 2 days. Shouldn't be a problem.

**Comment by giniedp** [comment]
Finally got some minutes to spare and filed a pull request on this.

**Comment by octogonz** [comment]
Great, thanks @giniedp!

**Comment by octogonz** [comment]
This was published as api-documenter 7.5.0
