### ISSUE TITLE
[api-documenter] MarkdownDocumenter: Links to referenced types in type cells

### ISSUE THREAD

**Issue by thorbenziemek** [microsoft/rushstack#1611]
**Is this a feature or a bug?**

- [x] Feature
- [ ] Bug

**Please describe the actual behavior.**
Types in generated Markdown documentation do not include links to type definitions automatically. For instance, in a class documentation, there is a column "Type" in the properties table, which in my case always only contains the plain name of the referenced type.

**What is the expected behavior?**
I would expect the mentioned type cells to include a link to the type definition, if applicable. From what I understand so far, this could be possible in the _createPropertyCell function (https://github.com/microsoft/rushstack/blob/589608e25a9a05d9f948c66c8f563f7834628760/apps/api-documenter/src/documenters/MarkdownDocumenter.ts#L805). Maybe loop over the excerpt's tokens and create a link to the type from the canonicalReferences. However, this would require something like `getLinkFilenameForDeclarationReference(canonicalReference)`. Is this possible to implement / any ideas on this?

**Comment by octogonz** [comment]
PR https://github.com/microsoft/rushstack/pull/1337 already implemented this for the DocFX target. We very much want to support it for Markdown as well, just haven't gotten around to it yet.

If you're interested in helping out, that would be awesome! (I'm reachable on [Gitter](https://gitter.im/octogonz) if you have questions about the design.)

**Comment by octogonz** [comment]
> However, this would require something like `getLinkFilenameForDeclarationReference(canonicalReference)`. Is this possible to implement / any ideas on this?

This problem is slightly complicated because we're halfway done revising the declaration references.

In the old model, API items were identified using TSDoc's `DocDeclarationReference` which is what you give to [ApiModel.resolveDeclarationReference()](https://github.com/microsoft/rushstack/blob/16c6a7e36f5d67c4aae8dda17b7052e6ddb3ce4e/apps/api-extractor-model/src/model/ApiModel.ts#L140).  But @rbuckton recently redesigned the grammar, and so the `canonicalReference` field is currently represented using his [DeclarationReference](https://github.com/microsoft/tsdoc/blob/3e72e621e746590f606a2132e7fb59400c746545/tsdoc/src/beta/DeclarationReference.ts#L17) class from the TSDoc library.  The ideal long term solution is to implement an equivalent of `ApiModel.resolveDeclarationReference()` that uses the `canonicalReference` objects.

The DocFX implementation was conveniently able to sidestep this part, because DocFX itself supports hyperlinking based on string IDs.

I feel like we could achieve something similar by having `ApiModel` track a simple mapping from `canonicalReference` --> `ApiItem`.  This hack wouldn't support partial lookups, but that's not a problem because the .api.json `canonicalReference` always stores fully qualified forms.

I can help with that part, if you're able to do the front-end work of emitting Markdown hyperlinks for each token.

**Comment by thorbenziemek** [comment]
Thank you @octogonz for the clarification! From what I understand, implementing the Markdown part should be super easy, so I would be happy to help with that part ;).

**Comment by octogonz** [comment]
This fix was published with API Documenter 7.8.0
