### ISSUE TITLE
[rush] configurable commit message for rush version --bump

### ISSUE THREAD

**Issue by mscharley** [microsoft/rushstack#1842]
**Is this a feature or a bug?**

- [x] Feature
- [ ] Bug

**Please describe the actual behavior.**

Currently rush uses a fixed commit message during the `rush version --bump` workflow:

https://github.com/microsoft/rushstack/blob/626c8efae811650d9eb778386f31ffb393b43468/apps/rush-lib/src/cli/actions/VersionAction.ts#L215

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

**What is the expected behavior?**

It would be nice if this message was configurable, same as the final commit a few lines below it.

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** rush
* **Tool Version:** 5.23.1
* **Node Version:** 12.16.1
  * **Is this a LTS version?** Yes 
  * **Have you tested on a LTS version?** Yes
* **OS:** Windows 10 / Arch Linux

**Comment by octogonz** [comment]
+1 if someone wants to make a PR, we would accept it.  We already did something similar with `versionBumpCommitMessage` in https://github.com/microsoft/rushstack/issues/1030

**Comment by mscharley** [comment]
Oh nice, thanks for the reference point. I might take a shot at this this weekend.

**Comment by mscharley** [comment]
What should the new configuration be called? `gitPolicy.versionBumpCommitMessage` already exists though it would probably be more accurate for this option. `gitPolicy.changelogCommitMessage` perhaps?

**Comment by octogonz** [comment]
From what I can tell, `gitPolicy.versionBumpCommitMessage` is used when the `package.json` version numbers are incremented.  It seems accurate to call that  "version bump."

Whereas the `Deleting change files` message is for the operation that generates new change logs and deletes the `rush change` files.  So your name makes sense to me.  

BTW I always thought of "change log" as being two words (`changeLog` instead of `changelog`).  But [Wikipedia](https://en.wikipedia.org/wiki/Changelog) writes it as one word.  It's tempting to search+replace the code base and make it one word everywhere...

**Comment by olivierlacan** [comment]
Looks like this was added and this issue can be closed, right? https://github.com/microsoft/rushstack/issues/2360

**Comment by mscharley** [comment]
Looks like it.
