### ISSUE TITLE
[api-extractor] Please support typescript 3.8

### ISSUE THREAD

**Issue by jrnail23** [microsoft/rushstack#1866]
**Is this a feature or a bug?**

- [x] Feature
- [ ] Bug

**Please describe the actual behavior.**

**What is the expected behavior?**

**Comment by octogonz** [comment]
Are there any new features in 3.8 that could potentially break API Extractor?

**Comment by jrnail23** [comment]
Yes, it seems that `import type { MyType } from "some-module"` breaks it (or at least that's what I think broke my setup).
I kept getting warnings falsely complaining that my types were missing a release/scope annotation (i.e., `@public`).

**Comment by octogonz** [comment]
Yeah, if that gets emitted in the .d.ts file, it might be a new import pattern.  API Extractor detects and walks each kind of import.

Some [3.8 features](https://devblogs.microsoft.com/typescript/announcing-typescript-3-8/) that might break something:
- ECMAScript private fields `class Person { #name: string }`
- `export * as utilities from "./utilities.js";` - in the past this had to be an import/export pair instead of one statement

From a quick glance at the [3.9 features](https://devblogs.microsoft.com/typescript/announcing-typescript-3-9/), I didn't see anything that looked like it would impact API Extractor.

**Comment by octogonz** [comment]
We can start work on a PR to add support for these issues. None of them seems particularly difficult.

But I should also point out:

- Using any of these features in your API might make your library unusable by consumers who haven't upgraded to the latest TypeScript compiler.
- A number of folks may be stuck on TypeScript 3.6 for a while, because TypeScript 3.7 [broke compatibility with all previous compiler releases](https://github.com/microsoft/TypeScript/issues/33939#issuecomment-562531198) even for code that doesn't use any 3.7 language features (!)

**Comment by MattiasBuelens** [comment]
> Using any of these features in your API might make your library unusable by consumers who haven't upgraded to the latest TypeScript compiler.

That's where a tool like [downlevel-dts](https://github.com/sandersn/downlevel-dts) can come in, to transform these new features into older syntax for older TypeScript versions. 😉 So you would first use API Extractor to create a `.d.ts` file for TypeScript 3.8, and then you would run downlevel-dts to create a variant for older TypeScript versions. 🙂

**Comment by octogonz** [comment]
TypeScript 3.9 introduces some new syntax also: https://github.com/microsoft/rushstack/issues/1914

**Comment by octogonz** [comment]
Some progress on this:
- Here's a PR that upgrades the compiler engine: https://github.com/microsoft/rushstack/pull/1983
- Here's a PR that adds support for `import type`: https://github.com/microsoft/rushstack/pull/1985

**Comment by octogonz** [comment]
- Here's a PR that adds support for ECMAScript private fields: https://github.com/microsoft/rushstack/pull/1987

With these changes, I think we can resolve this issue. There are still some remaining unsupported language features like https://github.com/microsoft/rushstack/issues/1914, but they have reasonable workarounds.

**Comment by octogonz** [comment]
These fix were released with API Extractor 3.9.0
