### ISSUE TITLE
[rush] change -v 0 exit code

### ISSUE THREAD

**Issue by Nojukubi** [microsoft/rushstack#1885]
- [ ] Feature
- [x] Bug

`rush change -v` always return 0 exit code.
It make sense to return other code in case no changes found, as it's breaking CI.

*Tool:* Rush
*Tool Version:* 5.23.4
*Node Version:* any
*OS:* Mac OS

**Comment by octogonz** [comment]
The expected behavior: If there are no changes, then `rush change -v` returns exit code 0. If changes ARE found (i.e. the person forgot to run `rush change` and commit the result), then the exit code is 1, which will break the CI build.

1. Are you observing something different?
2. If so, can you provide a repro?

**Comment by Nojukubi** [comment]
Sorry my misuse of rush, everything is ok
