### ISSUE TITLE
[rush] Command rush can not be found when running through install-run-rush.js

### ISSUE THREAD

**Issue by ghaiklor** [microsoft/rushstack#1917]
**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**

When running custom CLI command that uses `rush` underneath through `common/scripts/install-run-rush.js` it can not locate the `rush` command.

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

Here is a reproducible minimal configuration:

```
{
  "$schema": "https://developer.microsoft.com/json-schemas/rush/v5/command-line.schema.json",
  "commands": [
    {
      "allowWarningsInSuccessfulBuild": false,
      "commandKind": "global",
      "description": "This command will clean everything and run the whole build pipeline",
      "name": "all",
      "safeForSimultaneousRushProcesses": true,
      "shellCommand": "rush clean && rush rebuild && rush test && rush lint",
      "summary": "Clean & Run the entire build pipeline (clean, build, test, lint) for all projects"
    }
  ]
}
```

The repository itself - https://github.com/ghaiklor/kittik/tree/3c2e8a212bfffede78c99bdb8dfdbe72f030ec3f
Link to the build - https://travis-ci.com/github/ghaiklor/kittik/jobs/344358951

Now, when running it like `node common/scripts/install-run-rush.js all` it can not find executable `rush`.

**What is the expected behavior?**

`rush` can be found and all the sub-tasks from Rush can be executed.

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** Rush
* **Tool Version:** 5.24.3
* **Node Version:** v14.3.0
  * **Is this a LTS version?** pre-LTS
  * **Have you tested on a LTS version?** Yes
* **OS:** MacOS 10.15.5

**Comment by octogonz** [comment]
The appropriate PATH for `rush`  can be in different places depending on how Rush was invoked:

- `C:\Program Files\nodejs\rush.cmd` if the global Rush was the correct version
- `C:\Git\rushstack\common\temp\install-run\@microsoft+rush@5.23.0\node_modules\.bin\rush.cmd` if Rush was invoked via **install-run-rush.js**

Seems like Rush can detect the right PATH from its own `process.argv`.  So we just need to append (prepend?) this to the PATH when we invoke those commands.

**Comment by octogonz** [comment]
@ghaiklor would you be interested to make a PR?

**Comment by ghaiklor** [comment]
Sure, just point me, where is the PATH resolve process is happening. Should it be placed in `install-run.js` file? If so, maybe a workaround like `process.env.PATH = `${process.env.PATH}:common/temp/install-run/..../rush.js``?

**Comment by octogonz** [comment]
🤔 Interesting. That might actually be simpler. I was imagining we'd need to fix up the PATH for the `C:\Program Files\nodejs\rush.cmd` case as well.  In which case the fix would happen where `rush-lib` calls `Utilities.executeLifecycleCommand()`. But probably that already works (otherwise how was `rush.cmd` invoked?)

So yeah maybe we can fix this in `install-run-rush`.  That code is here:

https://github.com/microsoft/rushstack/blob/master/apps/rush-lib/src/scripts/install-run-rush.ts

And the helper library that it invokes simply reuses `process.env`:

https://github.com/microsoft/rushstack/blob/41968e733fbe3c23c187d26acdb8716739b0dcc1/apps/rush-lib/src/scripts/install-run.ts#L440-L448

So maybe you could patch up `process.env` in **install-run-rush.ts** before it calls `installAndRun()`.

> Sure, just point me, where is the PATH resolve process is happening. Should it be placed in `install-run.js` file? If so, maybe a workaround like `process.env.PATH = '${process.env.PATH}:common/temp/install-run/..../rush.js'`?

The specific path we want to calculate will look something like this:
```
C:\Git\rushstack\common\temp\install-run\@microsoft+rush@5.23.0\node_modules\.bin\
```

**Comment by ghaiklor** [comment]
On it... yes, I think that just patching PATH variable to add an alternative PATH to rush if it is called through `install-run-rush.js` will be simpler.

**Comment by ghaiklor** [comment]
@octogonz PR is ready and green
