### ISSUE TITLE
[api-extractor] Properties on base interface aren't available

### ISSUE THREAD

**Issue by JustinBeckwith** [microsoft/rushstack#1944]
👋 Greetings folks!  Thanks again for the lovely tools, and the quick turn around time on my last issue :)

## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**
I am generating docs for an interface that belongs to a bundledPackage.  This interface has a single property, but extends an interface that has many more properties.  When the interface is rendered via `api-documenter`, only the single property on the interface (none of the inherited properties) are rendered:

![image](https://user-images.githubusercontent.com/534619/85101538-751a2280-b1b7-11ea-861f-67804ed78d77.png)

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

```
git clone git@github.com:JustinBeckwith/extractor-issues.git
cd extractor-issues
npm install
npm run extract
npm run docs
```

Then open `docs/vision.streammethodoptions.md`

You can see the generated file here:
https://github.com/JustinBeckwith/extractor-issues/blob/master/docs/vision.streammethodoptions.md

And the interface it's trying to render here:
https://github.com/googleapis/nodejs-googleapis-common/blob/master/src/api.ts#L52

**What is the expected behavior?**
I would expect the properties on the base interface to be rendered, or for the generated document to have a link to the base interface.  

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:**  `@microsoft/api-extractor`
* **Tool Version:**  `7.8.12`
* **Node Version:** `v14.4.0`
  * **Is this a LTS version?** not yet
  * **Have you tested on a LTS version?** yes, 12
* **OS:** OSX

**Comment by octogonz** [comment]
> only the single property on the interface (none of the inherited properties) are rendered

This was part of the initial design because the DocFX template we originally targeted did not have a way to show inherited properties. (I'm not sure if it does today either -- @rbuckton do you know?)

We can implement this for the markdown target pretty easily, though.

>  or for the generated document to have a link to the base interface.

This was recently implemented for the DocFX target ([example here](https://github.com/microsoft/rushstack/blob/14e386e32696f7cddabd1eaa6a2c4993b3da9a5a/build-tests/api-documenter-test/etc/yaml/api-documenter-test/idocinterface2.yml#L10)).  Should be pretty quick to wire it up for Markdown.

**Comment by octogonz** [comment]
Ah right, now I remember that we also wanted the signature to have hyperlinks to the referenced types. For example `MethodOptions` should be a hyperlink in this example:

> ## StreamMethodOptions interface
> 
> <b>Signature:</b>
> 
> ```typescript
> export interface StreamMethodOptions extends MethodOptions 
> ```

However Markdown does not provide a way to make hyperlinks inside a code block:
````
```typescript
export interface StreamMethodOptions extends MethodOptions 
```
````

For example, something like this doesn't work:

````
```typescript
export interface StreamMethodOptions extends [MethodOptions](./MethodOptions.md) 
```
````

**Comment by rbuckton** [comment]
IIRC, the way DocFX would handle showing inherited members inline in the same page would be for the inherited members to be included in the `.yaml` file (with a note included in the description), for example:

![image](https://user-images.githubusercontent.com/3902892/85180858-5bb9ba80-b239-11ea-9b10-b669bd81e53f.png)

Which means `api-documenter` would have to include the inherited properties in the yaml file.

For the .NET documentation it also looks like they *don't* include the inherited members in the TOC entry for the class/interface, just in the overview page:

![image](https://user-images.githubusercontent.com/3902892/85181023-ce2a9a80-b239-11ea-8f25-b6834df6ee95.png)

**Comment by octogonz** [comment]
@JustinBeckwith for this input:

```
export declare class AuthPlus extends GoogleAuth 
    implements IExample, IExample2 {
    JWT: typeof JWT;
    Compute: typeof Compute;
    . . .
}
```
...I'm proposing to emit Markdown like this:

> ## AuthPlus class
> 
> <b>Signature:</b>
> 
> ```typescript
> export declare class AuthPlus extends GoogleAuth 
>    implements IExample, IExternalThing
> ```
> 
> **Extends:** [GoogleAuth](http://example.com)
>
> **Implements:** [IExample](http://example.com), IExternalThing
>
> ## Properties
> 
> |  Property | Modifiers | Type | Description |
> |  --- | --- | --- | --- |
> |  [Compute](./vision.authplus.compute.md) |  | typeof Compute |  |
>
> . . .

(and something similar for `interface` APIs.)  This should be quite easy because the information is already there in the .api.json file.

Would that work for you?

### Related possible improvements:

- We could also show "things that extend from this API" and "things that implement this `interface`", but the list would be incomplete; it would only include declarations that appear in the .api.json file set.

- We could also expand the **Properties** table to include inherited members (as you suggested) but using the current .api.json schema, it would omit members of APIs that are missing from the .api.json file set. (Missing members could be a misleading/confusing experience.) A concrete example is your `class GaxiosError<T = any> extends Error` API, since `Error` is a system class.  We could solve this by improving API Extactor to store inherited signatures in the  .api.json file somehow, but is it okay for the docs to be missing?

If you want to pursue these enhancements, please open separate GitHub issues to discuss the approach.  We'll close #1944 with the limited fix proposed above.

**Comment by octogonz** [comment]
I noticed that DocFX can show the entire **"Inheritance"** chain, [for example](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.button?view=netcore-3.1):

![Capture](https://user-images.githubusercontent.com/4673363/85181377-a0922100-b23a-11ea-9839-1090a83dbad6.png)

That would be a cool option as well, but again the .api.json schema only records one step in the chain, and thus we cannot discover declarations that don't appear in the file set.

**Comment by octogonz** [comment]
CC @acchou who I think was interested in this for the faast.js docs

**Comment by octogonz** [comment]
Here's a PR: https://github.com/microsoft/rushstack/pull/1947

@JustinBeckwith  I will wait for your feedback before merging

**Comment by JustinBeckwith** [comment]
This is an amazing first step!  I guess as a first goal, I'm looking for completeness.  This implementation is complete, and if the user clicks enough, they can get to all of the information they need.  

The main thing I'm concerned with is usability.  Trying to put myself in the shoes of a user - imagine you're calling a method like this:

```js
const res = await drive.files.list({
  query: 'filter123',
  oauthToken: '12345'
});
```

In this specific example, this would be a `Schema$DriveFilesList` interface, which provides the `query` property, and a `StandardParameters` interface that provides the `oauthToken` property.  As the user, I'm more concerned with seeing "what properties can I pass into this thing" than specifically which interface the property belongs to.  I think that would provide the best experience, but I'm super appreciative of the solution you're working towards.

I would love to see every property on the interface called out, with a bonus description somewhere on the property that shows where the property comes from.

If you'd like, I'd be more than happy to open a new issue to discuss!

**Comment by octogonz** [comment]
> If you'd like, I'd be more than happy to open a new issue to discuss!

Let's do that. Your scenario sounds important and fairly focused, so hopefully not too much work to solve.

Some design questions are:
- How do we indicate inherited properties in the template? (basically a mockup of the expected Markdown output)
- Do we need API Extractor to crawl signatures inherited from external libraries? If so, how is that represented in the .api.json file format? How do we avoid O(n^2) duplication of signatures?
   - Or if not, how do we avoid confusion when certain inherited properties are omitted because they came from an external library?
- Is it okay for all the external library properties to be missing docs, since .api.json files were not generated for them? (I know `@types` libraries often include doc comments, but there can be a copyright concern with reproducing that content on a documentation website.)

**Comment by JustinBeckwith** [comment]
Y'all rock. Thank you!
