### ISSUE TITLE
[rush] Give rush deploy the ability to select a subset of dependencies to copy over 

### ISSUE THREAD

**Issue by willsoto** [microsoft/rushstack#1978]
search terms: docker, dockerfile, development only

**Is this a feature or a bug?**

- [x] Feature
- [ ] Bug

**Please describe the actual behavior.**

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

Possibly related to #1943 and builds on the same [reproduction repo](https://github.com/willsoto/rush-dep-repro). You can see the changes via [this commit.](https://github.com/willsoto/rush-dep-repro/commit/0489288b1bf6c32235e319ea3c875eff156812bf)

After our discussion on gitter @octogonz, I decided to follow your advice and copy over the entire topology into an image to see how far I could get understanding that things were still "broken" until #1942 and #1943 is resolved.

Here are the steps to reproduce:

1. `rush update`
2. `rush build`
3. `rush deploy`
4. `docker build . --tag rush-dep-repro:latest`
5. `docker run -it --rm rush-dep-repro:latest sh`

The expectation is that the following lines in the `Dockerfile` would copy over all the required files in order to symlink in the image correctly:

```Dockerfile
COPY ./common/deploy/common .
COPY ./common/deploy/deploy-metadata.json .
COPY ./common/deploy/create-links.js .
```

When you get into the container via `docker run`, you can `ls -lah node_modules` and notice that all of the symlinks are broken. 

This behavior is confirmed when you attempt to run `npm run start:prod` - it fails to run because it cannot find the first module it attempts to load.

**What is the expected behavior?**

I should be able to symlink `node_modules` in the image or have some other mechanism for deploying the app via docker using the `rush deploy` feature.

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** pnpm
* **Tool Version:** 5.2.6
* **Node Version:** 12.x
  * **Is this a LTS version?** yes
  * **Have you tested on a LTS version?** yes
* **OS:** MacOS (in the image Alpine)

**Comment by octogonz** [comment]
> ```dockerfile
> COPY ./common/deploy/common .
> COPY ./common/deploy/deploy-metadata.json .
> COPY ./common/deploy/create-links.js .
> ```

The above seems incorrect. Shouldn't it say:

```dockerfile
COPY ./common/deploy .
```

The **common/deploy** folder tree is meant to be the complete file set that you deploy to docker (aside from the links, which you are creating using `create-links.js`).  Generally there won't be a simple way to extract a subset or rearrange the folders.

People have been asking for an **enhancement**, where `rush deploy` would rearrange the folder structure so that `apps/api` becomes the root folder that you deploy (i.e. `common` becomes a subfolder). This is nice-to-have, but it is not implemented yet (since it's not required to successfully deploy an app).

**Comment by willsoto** [comment]
@octogonz you are right and that _does_ fix the immediate issue.

 For some context: the reason I didn't just do `COPY ./common/deploy .` is because there are a lot of additional _development_ files that I don't want copied over into the final image (helps to keep the image size down). 

So my question is: _What files/folders is `COPY ./common/deploy .` capturing that the other 3 commands are not?_ Is there something I am not copying from the `api` folder that I should be?

**Comment by willsoto** [comment]
FWIW, this is the resulting topology on the image:

```
/opt/deploy $ tree .
.
├── apps
│   └── api
│       ├── dist
│       │   ├── app.controller.d.ts
│       │   ├── app.controller.js
│       │   ├── app.controller.js.map
│       │   ├── app.module.d.ts
│       │   ├── app.module.js
│       │   ├── app.module.js.map
│       │   ├── app.service.d.ts
│       │   ├── app.service.js
│       │   ├── app.service.js.map
│       │   ├── main.d.ts
│       │   ├── main.js
│       │   ├── main.js.map
│       │   └── tsconfig.build.tsbuildinfo
│       ├── node_modules
│       │   ├── @nestjs
│       │   │   ├── common -> /opt/deploy/common/temp/node_modules/.pnpm/@nestjs/common@7.2.0_b3556d138b40afc7ad37744b780e54fd/node_modules/@nestjs/common
│       │   │   ├── core -> /opt/deploy/common/temp/node_modules/.pnpm/@nestjs/core@7.2.0_e58e54e297611ab92294268e184fafe2/node_modules/@nestjs/core
│       │   │   ├── graphql -> /opt/deploy/common/temp/node_modules/.pnpm/@nestjs/graphql@7.4.1_d9776d8df05615f886c33564b99f3d72/node_modules/@nestjs/graphql
│       │   │   └── platform-express -> /opt/deploy/common/temp/node_modules/.pnpm/@nestjs/platform-express@7.2.0_145912070358fe5ce88022d5bfb62454/node_modules/@nestjs/platform-express
│       │   ├── class-transformer -> /opt/deploy/common/temp/node_modules/.pnpm/class-transformer@0.2.3/node_modules/class-transformer
│       │   ├── class-validator -> /opt/deploy/common/temp/node_modules/.pnpm/class-validator@0.12.2/node_modules/class-validator
│       │   ├── graphql -> /opt/deploy/common/temp/node_modules/.pnpm/graphql@14.2.1/node_modules/graphql
│       │   ├── graphql-tools -> /opt/deploy/common/temp/node_modules/.pnpm/graphql-tools@6.0.10_graphql@14.2.1/node_modules/graphql-tools
│       │   ├── nest-raven -> /opt/deploy/common/temp/node_modules/.pnpm/nest-raven@6.0.0-alpha.2_@nestjs+graphql@7.4.1/node_modules/nest-raven
│       │   ├── reflect-metadata -> /opt/deploy/common/temp/node_modules/.pnpm/reflect-metadata@0.1.13/node_modules/reflect-metadata
│       │   ├── rimraf -> /opt/deploy/common/temp/node_modules/.pnpm/rimraf@3.0.2/node_modules/rimraf
│       │   └── rxjs -> /opt/deploy/common/temp/node_modules/.pnpm/rxjs@6.5.5/node_modules/rxjs
│       └── package.json
├── common
│   └── temp
│       └── node_modules
├── create-links.js
├── deploy-metadata.json
└── temp
    └── node_modules

10 directories, 28 files
```

And if I `ls common/temp/node_modules` or `ls temp/node_modules` and look around it seems like everything is there.

**Comment by octogonz** [comment]
>  For some context: the reason I didn't just do `COPY ./common/deploy .` is because there are a lot of additional _development_ files in there that I don't want copied over into the final image (helps to keep the image size down).

@willsoto We could fine-tune what `rush deploy` copies by providing some settings for additional filtering beyond the basic settings `includeDevDependencies`, `includeNpmIgnoreFiles`, and `deploymentProjectNames`.

Unfortunately I don't have a whole lot of time to study your repro.  Maybe you could audit the extra files being copied, and write up a summary of:

- What kinds of files are they? (with some concrete examples)  Are they NPM dependencies, or loose files?
- Which ones have the biggest impact on your installation footprint?
- How could we tell `rush deploy` to omit them? (e.g. a `deploy.json` setting, or maybe a `.deployignore` file that does more than `.npmignore` which is already supported, etc)

**Comment by willsoto** [comment]
> Maybe you could audit the extra files being copied, and write up a summary of:
> * What kinds of files are they? (with some concrete examples) Are they NPM dependencies, or loose files?

I actually like the idea of `rush deploy` being able to selectively copy over files - trying to selectively `COPY` is a hacky workaround. In an ideal world I would simply do `COPY ./common/deploy .` as you suggest. So I don't think it's worth digging into the issue here.

> Which ones have the biggest impact on your installation footprint?

I wouldn't say it's just a handful of big files or anything - it's more death by a thousand cuts. There are all the various dotfiles (`eslint`, `prettier`), source files (the source typescript) etc. Individually they might be small but they start to add up. 

> How could we tell rush deploy to omit them? (e.g. a deploy.json setting, or maybe a .deployignore file that does more than .npmignore which is already supported, etc)

I really like the idea of a setting in `deploy.json`. Maybe something like `ignorePaths` which could accept glob patterns relative to the root of the project(s) being deployed.

Here are a couple of use cases to consider:

I have an `api` written in typescript. As part of the build phase I compile all my typescript (potentially including directories and files outside of `src`). The only things I'd like deployed (copied) for this package are `dist`, `folderA/*.js`, rootFileB.js`, `package.json` and its `node_modules`.

I have a `client` written in typescript (let's say a react app). This app is totally static and does not require a runtime. As part of the build phase, all the source code is compiled into `dist`. The only things I'd like deployed (copied) for this package are `dist` (no `node_modules` since no runtime is required)

Are either of these cases doable today? Seems like the `npmignore` might solve the `api` case, but not the `client` case?

**Comment by octogonz** [comment]
What you are describing is exactly the problem that .npmignore solves. It is probably a complete solution, unless you have a project that is /also/ published to an NPM registry /and/ requires different filtering for that case. (Give it a try -- I'd be very interested to hear what wasn't solvable by .npmignore)

There is a classic problem with .npmignore though, which is that the patterns are backwards. It should have been called .npminclude, not .npmignore, because when publishing you really do not want to accidentally include some random file you didn't intend to ship. We deal with that by [negating all the patterns] (https://github.com/microsoft/rushstack/blob/master/libraries/node-core-library/.npmignore). So if we want to make a deploy-specific file, I wonder if it maybe should be .deployinclude instead of .deployignore. (?)

**Comment by octogonz** [comment]
To clarify, a suggested design would be:

1. If .deployinclude exists in the project root folder, use that for filtering, otherwise
2. If .npmignore exists (and is not disabled by deploy.json), use that, otherwise
3. Perform only minimal filtering similar to what `npm publish` does

(2 and 3 are already implemented)

**Comment by willsoto** [comment]
> What you are describing is exactly the problem that .npmignore solves. It is probably a complete solution, unless you have a project that is /also/ published to an NPM registry /and/ requires different filtering for that case.
> 
> (Give it a try -- I'd be very interested to hear what wasn't solvable by .npmignore)
> 

`npmignore` actually does basically solve my original problem. The one pending thing I would say is `node_modules` from `client` being included in the resulting `deploy` folder. Is that possible via `.npmignore`?

**Comment by octogonz** [comment]
Normally node_modules is managed by marking certain dependencies as `devDependencies` in your package.json. Glob filtering would not be recommended for node_modules paths because they are a delicate data structure owned by the package manager (and crawled separately by `rush deploy`).

If you want to omit the ENTIRE folder, I suppose deploy.json could have a special project-specific setting such as "ignoreAllDependencies". This could be useful if there is some reason why you cannot make them `devDependencies`.

**Comment by willsoto** [comment]
`ignoreAllDependencies` could really be all we need here honestly.

I understand the tension from a purely technical perspective since everything is a `devDependency` in the case of the client since it has no runtime. But from a non-technical perspective, having the distinction between dependencies (ie these things _are_ used in application code) vs devDependencies (ie these things _are not_ used in application code) is useful as a maintainer. Would you agree?

**Comment by octogonz** [comment]
That does make sense for a bundled application.

Another possible design would be an optional explicit "deployDependencies" list that takes precedence over the regular package.json dependencies. Then instead of `ignoreAllDependenices=true`, you would set `deployDependencies=[]`. This might be more flexible for cases where only certain dependencies get bundled.

**Comment by willsoto** [comment]
That’s great. And by default that would “equal” ‘dependencies’?

**Comment by willsoto** [comment]
@octogonz any more thoughts? I'd also be willing to take a stab at a PR here if the difficulty is considering easy or medium.

Would we get the ability to configure `deployDependencies` even for projects specified here:

https://github.com/microsoft/rushstack/blob/2b06f26d1f7a67351a58adea2c1bff1f0fbe09cf/apps/rush-lib/assets/rush-init-deploy/scenario-template.json#L73-L75

**Comment by octogonz** [comment]
I worked through the design a bit more, and came up with 3 filtering fields that work together like this:

```js
  "projectSettings": [
    // {
    //   /**
    //    * The full package name of the project, which must be declared in rush.json.
    //    */
    //   "projectName": "@my-scope/my-project",
    //
    //   /**
    //    * A list of additional local Rush projects to be deployed with this project (beyond the package.json
    //    * dependencies).  Specify full package names, which must be declared in rush.json.
    //    */
    //   "additionalProjectsToInclude": [
    //     // "@my-scope/my-project2"
    //   ],
    //
    //   /**
    //    * When deploying a project, the included dependencies are normally determined automatically based on
    //    * package.json fields such as "dependencies", "peerDependencies", and "optionalDependencies",
    //    * subject to other deployment settings such as "includeDevDependencies".  However, in cases where
    //    * that information is not accurate, you can use "additionalDependenciesToInclude" to add more
    //    * packages to the list.
    //    *
    //    * The list can include any package name that is installed by Rush and resolvable via Node.js module
    //    * resolution; however, if it resolves to a local Rush project, the "additionalProjectsToInclude"
    //    * field will not be recursively applied.
    //    */
    //   "additionalDependenciesToInclude": [
    //     // "@rushstack/node-core-library"
    //   ],
    //
    //   /**
    //    * This setting prevents specific dependencies from being deployed.  It only filters dependencies that
    //    * are explicitly declared in package.json for this project.  It does not affect dependencies added
    //    * via "additionalProjectsToInclude" or "additionalDependenciesToInclude", or does it affect indirect
    //    * dependencies.  
    //    *
    //    * The "*" wildcard may be used to match zero or more characters.  For example, if your project already
    //    * bundles its own dependencies, specify "dependenciesToExclude": [ "*" ] to exclude all package.json
    //    * dependencies.
    //    */
    //   "dependenciesToExclude": [
    //     // "@types/*"
    //   ]
    // }
  ]
```

For even more complex problems, I'm thinking we would introduce a **pnpmfile-deploy.js** that overrides **pnpmfile.js** during deployment.  But that should be a last resort, since JSON fields are much easier to manage.

If you like this overall design, your PR doesn't need to implement everything today.  Your scenario is solvable with only `"dependenciesToExclude": [ "*" ]`.

Ideally we'd want `*` to be a [glob](https://www.npmjs.com/package/glob), however we'd need to carefully craft that to avoid the need for glob escaping -- i.e. disable any glob operators that are legal NPM package name characters.  

To avoid that hassle, this really simple design is sufficient (and forwards compatible with globs):

```ts
function escapeRegExp(literal: string) {
    return literal.replace(/[^A-Za-z0-9_]/g, '\\$&');
}

function matchesWithStar(patternWithStar: string, input: string): boolean {
  // Map "@types/*" --> "^\@types\/.*$"
  const pattern: string = '^'
    + patternWithStar.split('*').map(x => escapeRegExp(x)).join('.*')
    + '$';
  const regExp = new RegExp(pattern);
  return regExp.test(input);
}

// Prints true
console.log(matchesWithStar('@types/*', '@types/blah'));
```

**Comment by octogonz** [comment]
>  I'd also be willing to take a stab at a PR here if the difficulty is considering easy or medium.

Awesome!  The implementation is probably not too involved. For an example of how to introduce a new setting, take a look at PR https://github.com/microsoft/rushstack/pull/2008 which adds a `postCopySourceFolder` setting.

**Comment by willsoto** [comment]
@octogonz one question I have regarding the design is whether or not it will support filtering dependencies for projects declared in the `additionalProjectsToInclude`. For example, given the following `deploy.json`

```json
{
  "$schema": "https://developer.microsoft.com/json-schemas/rush/v5/deploy-scenario.schema.json",
  "deploymentProjectNames": ["api"],
  "projectSettings": [
    {
      "projectName": "api",
      "additionalProjectsToInclude": [
        "client"
      ]
    }
  ]
}
```

How would I specify `dependenciesToExclude: ["*"]` for `client` only?

**Comment by octogonz** [comment]
@willsoto you would add a separate entry under `projectSettings` with      `"projectName": "client",`. Does that make sense?

**Comment by willsoto** [comment]
Yup! Makes sense.

**Comment by willsoto** [comment]
So I've been researching where in the code I'd actually do the work and this is the section that currently deals with dependencies:

https://github.com/microsoft/rushstack/blob/e072acfacdb3979b55f5f4f7e5ebd2e53b6a2c31/apps/rush-lib/src/logic/deploy/DeployManager.ts#L141-L168

Would you expect the logic to go there? 

Some other questions:

1. Did you have any thoughts about precedence? eg, if a user specifies `includeDevDependencies` but also excludes dev dependencies via `dependenciesToExclude`, what wins?
2. What about conflicts between `additionalDependenciesToInclude` and `dependenciesToExclude`? Raise an error? 
3. I assume we are filtering based on the total set of dependencies, ie `dependencies | devDependencies | optionalDependencies`, is that right?

**Comment by octogonz** [comment]
>     1. Did you have any thoughts about precedence? eg, if a user specifies `includeDevDependencies` but also excludes dev dependencies via `dependenciesToExclude`, what wins?

The `dependenciesToExclude` should take precedence over `includeDevDependencies` because it is a narrower scope:
- it is specified per-project, whereas `includeDevDependencies` is global
- `dependenciesToExclude` specifies individual names or patterns, whereas `includeDevDependencies` is `*`

(Generally narrower scope should get precedence, so you can use it to refine a broader scope.)

>     2. What about conflicts between `additionalDependenciesToInclude` and `dependenciesToExclude`? Raise an error?

The `includeDevDependencies` should win, because it always specifies actual packages, whereas `dependenciesToExclude` can have loose wildcards.

I tried to explain that here; feel free to improve the wording:
```
    //   /**
    //    * This setting prevents specific dependencies from being deployed.  It only filters dependencies that
    //    * are explicitly declared in package.json for this project.  It does not affect dependencies added
    //    * via "additionalProjectsToInclude" or "additionalDependenciesToInclude", nor does it affect indirect
    //    * dependencies.  
```

>     3. I assume we are filtering based on the total set of dependencies, ie `dependencies | devDependencies | optionalDependencies`, is that right?

Right.  More specifically:

> Would you expect the logic to go there?

Yup!  I'm thinking your algorithm would add/remove items to the `allDependencyNames` set after it is built, and before `this._traceResolveDependency()` is called.  

You can look up information about a folder like this:
https://github.com/microsoft/rushstack/blob/e072acfacdb3979b55f5f4f7e5ebd2e53b6a2c31/apps/rush-lib/src/logic/deploy/DeployManager.ts#L296-L298

And you can access the `projectSettings` like this: 
https://github.com/microsoft/rushstack/blob/e072acfacdb3979b55f5f4f7e5ebd2e53b6a2c31/apps/rush-lib/src/logic/deploy/DeployManager.ts#L441-L445

As I recall `_collectFoldersRecursive()` doesn't easily know whether it is looking at a local Rush project folder or a `node_modules` dependency.  So maybe you might add `projectSettings: IDeployScenarioProjectJson` directly to `IFolderInfo` if that makes things easier. (?)
