### ISSUE TITLE
[rush] rush deploy does not copy over package binaries

### ISSUE THREAD

**Issue by willsoto** [microsoft/rushstack#1982]
**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**

When executing `package.json` `scripts`, the underlying binary cannot be found because the `.bin` folder has not been copied (which I think is where `npm` looks for binaries)

example stack trace trying to call `knex`

```
/opt/deploy/apps/api $ npm run db:migrate:prod

> api@0.0.1 db:migrate:prod /opt/deploy/apps/api
> knex migrate:latest --verbose

sh: knex: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! api@0.0.1 db:migrate:prod: `knex migrate:latest --verbose`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the api@0.0.1 db:migrate:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

1. Install any package that also installs a binary (eslint or prettier are both good choices). 
2. Create a `package.json` `script` that calls the binary. For example, create a script called `prettier` with the following content: `prettier src/**/* --write`
3. Confirm that `npm run prettier` and/or `rushx prettier` works while inside the app directly.
4. `rush build` && `rush deploy`
5. `cd common/deploy/apps/api` and run `npm run prettier` or `rushx prettier` 

From gitter, [this is how `rush install` does it](https://github.com/microsoft/rushstack/blob/040dc7ae65fb0102345570a967e5d490b4c166c3/apps/rush-lib/src/logic/pnpm/PnpmLinkManager.ts#L284)

**What is the expected behavior?**

Packages that install binaries should be included / symlinked / copied during the deploy process.

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** pnpm
* **Tool Version:** 5.2.6
* **Node Version:** 12.16.3
  * **Is this a LTS version?** yes
  * **Have you tested on a LTS version?** yes
* **OS:** MacOS and Alpine linux

**Comment by octogonz** [comment]
@willsoto If you are able to contribute a PR, here's a few pointers from an initial investigation.

1. We want to invoke `pnpmLinkBins()` like [rush install does](https://github.com/microsoft/rushstack/blob/040dc7ae65fb0102345570a967e5d490b4c166c3/apps/rush-lib/src/logic/pnpm/PnpmLinkManager.ts#L284), however that API is deeply `async`, whereas the `DeployManager` is currently 100% synchronous (a personal preference, since I find `async` code to be harder to debug and often slower).  Thus you'll need to convert the callstack to use `async/await` from [DeployAction.run()](https://github.com/microsoft/rushstack/blob/03633c4d2c2e44170a3aa69a7fda857eb3826f8e/apps/rush-lib/src/cli/actions/DeployAction.ts#L68) down to wherever you call `pnpmLinkBins()`. You don't need to convert every operation along the way -- I'm fine with keeping the code 99% synchronous.

2. The `@pnpm/link-bins` library is an old version. Might be a good idea to upgrade it, since it looks like that would give us https://github.com/pnpm/pnpm/commit/3130bf712bb082e1c24055ba8f93faf1d2cb5da8#diff-88e0a0f5d009d2fbe66ede64e09233ce which might fix some annoying warnings we've been seeing during `rush link`.

3. The obvious place to make the binaries is inside `DeployManager._deployFolder()`, however you'll find that `pnpmLinkBins()` expects a fully installed **node_modules** folder, which doesn't exist for a deployment until AFTER the links are created.  Thus this information actually needs to be deferred all the way to [here](https://github.com/microsoft/rushstack/blob/89076aee15970ccab968c6ca48b85fc7165359df/apps/rush-lib/src/logic/deploy/DeployManager.ts#L535), and also [here](https://github.com/microsoft/rushstack/blob/89076aee15970ccab968c6ca48b85fc7165359df/apps/rush-lib/src/scripts/create-links.ts#L86) for the **create-links.js** mode.

4. This also means you need to store the work to be performed in **deploy-metadata.json**.  This information boils down to the folder paths for the rush.json local projects that were deployed, i.e. those [IDeployState.folderInfosByPath](https://github.com/microsoft/rushstack/blob/89076aee15970ccab968c6ca48b85fc7165359df/apps/rush-lib/src/logic/deploy/DeployManager.ts#L99) with `isRushProject=true`.  I'd propose generalizing it a bit like this:

     **deploy-metadata.json**
     ```ts
    {
      "scenarioName": "deploy.json",
      "mainProjectName": "@microsoft/api-extractor",
      "projects": [
        { "path": "apps/api-extractor" }, // <--- relative path from common/deploy root
        { "path": "libraries/node-core-library" },
        . . .
      ],
      "links": [
        {
          "kind": "folderLink",
          "linkPath": "apps/api-extractor-model/node_modules/@microsoft/tsdoc",
          "targetPath": "common/temp/node_modules/.pnpm/registry.npmjs.org/@microsoft/tsdoc/0.12.19/node_modules/@microsoft/tsdoc"
        },
        . . . 
      ]
    }

     ```

5. I noticed that PNPM's binary wrappers contain absolute paths.  For eaxmple:

    **apps\api-extractor\node_modules\.bin\gulp.ps1**
    ```
    #!/usr/bin/env pwsh
    $basedir=Split-Path $MyInvocation.MyCommand.Definition -Parent

    $exe=""
    $env_node_path=$env:NODE_PATH
    $env:NODE_PATH="C:\Git\rushstack\common\temp\node_modules\.pnpm\registry.npmjs.org\gulp\4.0.2\node_modules\gulp\bin\gulp.js\node_modules \
    ;C:\Git\rushstack\common\temp\node_modules\.pnpm\registry.npmjs.org\gulp\4.0.2\node_modules\gulp\bin\node_modules \
    ;C:\Git\rushstack\common\temp\node_modules\.pnpm\registry.npmjs.org\gulp\4.0.2\node_modules\gulp\node_modules \
    ;C:\Git\rushstack\common\temp\node_modules\.pnpm\registry.npmjs.org\gulp\4.0.2\node_modules \
    ;C:\Git\rushstack\common\temp\node_modules\.pnpm\registry.npmjs.org\gulp\node_modules \
    ;C:\Git\rushstack\common\temp\node_modules\.pnpm\registry.npmjs.org\node_modules \
    ;C:\Git\rushstack\common\temp\node_modules\.pnpm\node_modules \
    ;C:\Git\rushstack\common\temp\node_modules \
    ;C:\Git\rushstack\common\node_modules \
    ;C:\Git\rushstack\node_modules \
    ;C:\Git\node_modules \
    ;C:\node_modules \
    ;C:\Git\rushstack\apps\api-extractor\node_modules\gulp\bin\gulp.js\node_modules \
    ;C:\Git\rushstack\apps\api-extractor\node_modules\gulp\bin\node_modules \
    ;C:\Git\rushstack\apps\api-extractor\node_modules\gulp\node_modules \
    ;C:\Git\rushstack\apps\api-extractor\node_modules \
    ;C:\Git\rushstack\apps\node_modules"
    if ($PSVersionTable.PSVersion -lt "6.0" -or $IsWindows) {
      # Fix case when both the Windows and Linux builds of Node
      # are installed in the same directory
      $exe=".exe"
    } else {
      $env:NODE_PATH="/mnt/c/Git/rushstack/common/temp/node_modules/.pnpm/registry.npmjs.org/gulp/4.0.2/node_modules/gulp/bin/gulp.js/node_modules \
    ;/mnt/c/Git/rushstack/common/temp/node_modules/.pnpm/registry.npmjs.org/gulp/4.0.2/node_modules/gulp/bin/node_modules \
    ;/mnt/c/Git/rushstack/common/temp/node_modules/.pnpm/registry.npmjs.org/gulp/4.0.2/node_modules/gulp/node_modules \
    ;/mnt/c/Git/rushstack/common/temp/node_modules/.pnpm/registry.npmjs.org/gulp/4.0.2/node_modules \
    ;/mnt/c/Git/rushstack/common/temp/node_modules/.pnpm/registry.npmjs.org/gulp/node_modules \
    ;/mnt/c/Git/rushstack/common/temp/node_modules/.pnpm/registry.npmjs.org/node_modules \
    ;/mnt/c/Git/rushstack/common/temp/node_modules/.pnpm/node_modules \
    ;/mnt/c/Git/rushstack/common/temp/node_modules \
    ;/mnt/c/Git/rushstack/common/node_modules \
    ;/mnt/c/Git/rushstack/node_modules \
    ;/mnt/c/Git/node_modules \
    ;/mnt/c/node_modules \
    ;/mnt/c/Git/rushstack/apps/api-extractor/node_modules/gulp/bin/gulp.js/node_modules \
    ;/mnt/c/Git/rushstack/apps/api-extractor/node_modules/gulp/bin/node_modules \
    ;/mnt/c/Git/rushstack/apps/api-extractor/node_modules/gulp/node_modules \
    ;/mnt/c/Git/rushstack/apps/api-extractor/node_modules \
    ;/mnt/c/Git/rushstack/apps/node_modules"
    }
    $ret=0
    if (Test-Path "$basedir/node$exe") {
      # Support pipeline input
      if ($MyInvocation.ExpectingInput) {
        $input | & "$basedir/node$exe"  "$basedir/../gulp/bin/gulp.js" $args
    ```

   Before proceeding too far, I'd suggest to test this and make sure these hardwired paths aren't problematic somehow in your Docker environment.

**Comment by willsoto** [comment]
@octogonz one question I do have is how to link the bins in `create-links.js`. I noticed this comment at the top: 

https://github.com/microsoft/rushstack/blob/89076aee15970ccab968c6ca48b85fc7165359df/apps/rush-lib/src/scripts/create-links.ts#L11-L12

In the `default` mode I am using `@pnpm/link-bins`, so is the expectation I do the same here? Do I inline the work with credit to the package? Other suggestions?

**Comment by octogonz** [comment]
@ujwal-setlur What you're asking for I believe was discussed in the PR review, but we decided it should be implemented as a separate PR.  See this comment: https://github.com/microsoft/rushstack/pull/2010#issuecomment-656900649

If you need it, please create a new GitHub issue asking for it, with some details about why you need it.

**Comment by ujwal-setlur** [comment]
@octogonz, fair enough. For now, I am using ``linkCreation: default``, tar/gzip to preserve links and transferring to target. That works. But it would be good to call this out somewhere in the docs, since it took me while to figure out why this was happening ;)

**Comment by octogonz** [comment]
@ujwal-setlur what happens in your case?  Are the `node_modules/.bin/` files simply missing?  Or are they generated, but they do not  work correctly?

**Comment by ujwal-setlur** [comment]
If I remember right, the ``.bin`` directory was just missing, but I am not entirely sure. This was for a NextJS project and I know that the ``next`` binary was missing. This is needed to run NextJS projects.

**Comment by octogonz** [comment]
I updated the docs in https://github.com/microsoft/rushjs.io-website/commit/1b06a687bb827c7c6213f39a65b82d159ab86cbc

**Comment by ujwal-setlur** [comment]
@octogonz thanks much! This was my first move into monorepo, and I was very hesitant, but I chose ``rush``, and so far I am loving it! Excellent support and community engagement!
