### ISSUE TITLE
[api-documenter] Fails at handling circular references

### ISSUE THREAD

**Issue by jsamr** [microsoft/rushstack#2157]
## [api-extractor] Fails at handling circular references

**Is this a feature or a bug?**

- [ ] Feature
- [X] Bug

**Failing snippet**

```ts
/** @public */
export interface A {
  /** {@link B.options} */
  readonly options: any;
}

/** @public */
export type B = {
  readonly options: any;
  /** {@link C.bar} */
  readonly bar: string;
};

/** @public */
export type C = {
  /** {@link A} */
  readonly script: string;
  readonly bar: string;
};
```

**Please describe the actual behavior.**

Process fails with exit code 1

The bug appears when running api-documenter after a successful `api-extractor run --local`. See the `build:source` and `build:defs` scripts in the corresponding project.

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

```sh
git clone https://github.com/jsamr/reproduction-api-documenter-circular.git
cd reproduction-api-documenter-circular
yarn install
yarn build
```

You should see in the console:

![2020-09-01-142212_627x130_scrot](https://user-images.githubusercontent.com/3646758/91885681-917a1700-ec5e-11ea-89c6-dc8fa17c8ee9.png)

**What is the expected behavior?**

Process exits successfully (exit code 0).

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** @microsoft/api-documenter
* **Tool Version:** 7.8.36
* **Node Version:** Both latest (14.8.0) and LTS (12.18.3)
  * **Is this a LTS version?** No
  * **Have you tested on a LTS version?** Yes (12.18.3)
* **OS:** Manjaro, latest updates, kernel 5.8.3-2

**Comment by octogonz** [comment]
This is actually a bug with formatting a warning message, not with the link resolution. We are calling `JSON.stringify()` on an object that is not intended to be JSON serializable.

If we fix that problem, then the warning is printed like this:
```
WARNING: Unable to resolve reference "B.options": Unable to resolve "options" because B cannot act as a container
```

In other words, API Extractor considers this declaration to be a type algebra expression:
```ts
/** @public */
export type B = {
  readonly options: any;
  /** {@link C.bar} */
  readonly bar: string;
};
```
It models `A.options` as an API item that is a member of `A`, whereas it models `B.options` as an anonymous subexpression (i.e. code fragment).  

The rationale is that if we treat `B.options` as an API item, then what about this:
```ts
/** @public */
export type B = ({
  readonly options: any;
  /** {@link C.bar} */
  readonly bar: string;
});
```
...or this:
```ts
/** @public */
export type B = {
  readonly options: any;
  /** {@link C.bar} */
  readonly bar: string;
} | { 
    options: number;  // a different thing also called "options"!
    baz: string 
};
```
There's a slippery slope of expressions that look like an `interface` but step further and further towards arbitrarily complex type algebra that cannot realistically be modeled by a documentation system.  It would be counterintuitive for a developer to take one of these small steps and then find that all of `B`'s members have suddenly disappeared from existence.

Thus, API Extractor historically has taken the position that if you want it to be documented like an `interface`, then simply use the `interface` keyword.  

We could consider relaxing/improving this design.  But it should be a separate GitHub issue, since the circular reference error is easily fixable.

**Comment by jsamr** [comment]
@octogonz Thanks for this thorough explanation! And btw, I want to thank you and your team for the time invested in this complex but thrilling project. It is so powerful, I have come to realize how easy it is to follow semantic versioning now thanks to api-extractor. Just `git diff latest etc/<package>.api.md`. Truly fantastic. Haven't check rush per se yet, but looks very nice too.

**Comment by octogonz** [comment]
@jsamr thanks for the kind words!  If you'd like a free API Extractor T-shirt, ping me on [Gitter](https://gitter.im/octogonz) or [Twitter](https://twitter.com/octogonz_). 🙂
