### ISSUE TITLE
[Heft] - Webpack task supports custom devServer options

### ISSUE THREAD

**Issue by alfonsoar** [microsoft/rushstack#2281]
**Is this a feature or a bug?**

- [x] Feature
- [ ] Bug

**Please describe the actual behavior.**

The Webpack task in Heft currently does not support custom `devServer` options. There is a TODO in order to allow these options to be made configurable [here](https://github.com/microsoft/rushstack/blob/master/apps/heft/src/plugins/Webpack/WebpackPlugin.ts#L59). 

**What is the expected behavior?**

Ideally, I think these options should be configurable by the developer via the *webpack.config.js* file.

For example something similar to this: 
```
module.exports = {
  //...
  devServer: {
    contentBase: path.join(__dirname, 'dist'),
    compress: true,
    port: 9000
  }
};
```

I am happy to work on this enhancement if this is indeed the right approach to take. 

**CC:** @iclanton & @octogonz

**Comment by iclanton** [comment]
That sounds like the right approach. I'm trying to remember why we did it this way, and the only thing I can think of is that because we aren't using the Webpack CLI under Heft's hood, there wasn't an easy way to get this out of the webpack config.

If you wouldn't mind investigating a fix and putting together a change, we'd certainly appreciate it.

**Comment by alfonsoar** [comment]
@iclanton - Certainly, I will look into this over the next few days and submit a PR.

**Comment by alfonsoar** [comment]
Not sure why github is not picking up the PR but I created one here https://github.com/microsoft/rushstack/pull/2287
