### ISSUE TITLE
[rush] support pnpm filter workspace packages

### ISSUE THREAD

**Issue by gfortaine** [microsoft/rushstack#2329]
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [x] Feature
- [ ] Bug

**Please describe the actual behavior.**

It looks like that we can't leverage the filter feature from pnpm even with useWorkspaces=true

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

One should be able to filter with rush when using pnpm.

**What is the expected behavior?**

`rushx --filter=@rushstack/heft build`

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** 
* **Tool Version:** 
* **Node Version:** 
  * **Is this a LTS version?** 
  * **Have you tested on a LTS version?** 
* **OS:**

**Comment by D4N14L** [comment]
Rush does support filtering installs when `useWorkspaces=true`, though more limited to ensure compatibility. It works much in the same way that filtering batch script commands in Rush:
```
rush install -t <project> / rush install --to <project>
rush build -t <project> / rush build --to <project>
```

Running `rush install --to <project>` is equivalent to doing `pnpm install --filter=<project>...` which will install that project, as well as all dependent projects in the monorepo.

**Comment by D4N14L** [comment]
Focusing on your specific example (a filter to a single project), that style of filtered install doesn't exist in Rush because it wouldn't make much sense in the context of the greater monorepo (ex. if your project depends on another local project, you would need to have dependencies of dependencies installed in order to perform your build successfully anyway).

For bulk script commands, Rush performs an incremental build. That is, all dependencies are built first before the target project is built. For subsequent builds, Rush will only execute the script command in projects that have changed (or have dependencies that have changed). If, for example, you did a `rush build -t <project>`, all dependencies would be built, then `<project>` would be built. On each subsequent `rush build -t <project>`, only that project will be built, assuming you are only making changes to that one project.

**Comment by D4N14L** [comment]
Going to close out this issue because I believe I answered your questions about this feature. Let me know if you still have any more or feel free to re-open.

**Comment by dbartholomae** [comment]
@D4N14L Is there a way to e.g. `rush install --to "...[origin/main]"`, which would only install packages that changed in the commits that are on top of the current main branch?
Pnpm supports this: https://pnpm.io/filtering#--filter-since

**Comment by dbartholomae** [comment]
Thanks, `--to git:origin/main` is already really helpful! I'll open a PR on the docs to add information about it.
I'll experiment with this a bit, but currently I think that `rush install --to git:origin/main` actually is what I need: I'm trying to limit our workflows to only install, build and test the things that actually changed - so installing only the changed packages and their dependencies is exactly what I want :)
