### ISSUE TITLE
[rush] Make it easier to invoke PNPM workspace commands

### ISSUE THREAD

**Issue by octogonz** [microsoft/rushstack#2347]
This is a feature request for Rush.

With the experimental new `useWorkspaces=true` setting in **rush.json**, it's now possible to let PNPM entirely manage installation and linking of Rush projects.  Rush will no longer create `common/temp` projects, nor will it create its own proprietary symlinks.

## Problem statement

However, workspace commands like `pnpm run` or `pnpm audit` cannot be invoked directly.

The reason is that PNPM expects a manually authored `pnpm-workspace.yaml`  file in the repo root. Whereas Rush creates a machine-generated `common/temp/pnpm-workspace.yaml` file.  Rush also wants the common `node_modules` folder to be installed as `common/temp/node_modules`, not in the repo root.

## Two possible approaches

1. One approach would to enable `pnpm` commands to simply work in Rush repos.  (There are various ways to approach this, e.g. improving PNPM to support alternate paths for `pnpm-workspace.yaml`, or finding a way to move that file to the repo root without impacting other Rush features.)  A downside of this approach is that Rush has features such as [preferred versions](https://rushjs.io/pages/advanced/preferred_versions/) and [installation variants](https://rushjs.io/pages/advanced/installation_variants/) that may not work correctly with arbitrarily PNPM commands.  For example, if `pnpm outdated` upgrades versions, it ideally should also upgrade files like `common-versions.json`.  And it should provide a way to update variant files as well.  Users might invoke PNPM without realizing this and end up with a corrupted working folder.

2. Another approach would be to wrap PNPM commands with corresponding Rush commands.  For example `rush outdated` instead of `pnpm outdated`.  We could also provide a general pass-through mechanism `rush pnpm` that will invoke `pnpm` against the  `common/temp/pnpm-workspace.yaml` file, but issue a warning for commands that are known to be problematic in a Rush repo.

Once we decide on the overall approach we want to take, then we can look at the engineering details required to make it work.

CC @D4N14L

**Comment by D4N14L** [comment]
Personally, I'm in favour of the latter option.
- PNPM is pretty bound to the concept that the `pnpm-lock.yaml` and `.npmrc` are in the root of the project (and the only way to configure PNPM options other than command-line args is through the `.npmrc` file)
  - You can move the workspaces file using a PNPM command-line arg, but the other two I think cannot be moved, which is why I had to go fix support for PNPM running installs outside of the directory tree that the `pnpm-lock.yaml` file sits in when I implemented workspaces
- Since Rush would have control over the utility, we could also do stuff like ensure that the install prep has been done before running the PNPM command, since we have a prepare stage that copies/generates required files in `common/temp`
  - There is also the concern that running PNPM commands directly can corrupt/modify your project in unintended ways. Through the tool, we can either augment how that command is run, or simply provide a warning to the dev about what they're about to do (like an exclusion list)

**Comment by octogonz** [comment]
I think I'm in favor of approach 2 also.

Maybe the initial design can be as simple as `rush pnpm [...]` will:

- Report a warning if the PNPM command is known to have issues in a Rush repo (e.g. `It's recommended to use "rush install" instead of "pnpm install"`).
- Ensure the `pnpm-workspace.yaml` file is up to date
- Invoke `pnpm [...]` using Rush's configuration
- (Maybe?) If PNPM modifies `common/temp` files, apply these changes appropriately (e.g. copy `pnpm-lock.yaml` -> `common/config/rush/pnpm-lock.yaml`)

**Comment by ksnyde** [comment]
the commands `outdated`, `ls`, and `why` are critically important to support ... I suspect that the FIRST approach is a needed first step. Later, if you want to provide the same syntax proxied via the `rush` CLI command than that would probably be helpful too. I'd have a hard time imagining, however, that you wouldn't have to solve **(1)** to solve **(2)**

**Comment by ksnyde** [comment]
As for easy or not easy ... i think this is TBD. If there's a configuration setting for PNPM (which typically just uses npm config) then let's get this closed as it's clearly easy but it would require internal workings of RushJS and how it alters the normal workings of `pnpm` to do this so I'm afraid I'd be fairly useless at this.

**Comment by octogonz** [comment]
If you run `rush install --debug-package-manager --purge` you can see the full CLI for PNPM:

```
Running "pnpm install" in C:\Git\rushstack\common\temp


Invoking package manager: 
C:\Users\username\.rush\node-v14.15.3\pnpm-4.14.4\node_modules\.bin\pnpm install 
--store C:\Git\rushstack2\common\temp\pnpm-store --no-lock --no-prefer-frozen-lockfile 
--reporter ndjson --strict-peer-dependencies --resolution-strategy=fewer-dependencies 
--recursive --link-workspace-packages false
```

The generated file `C:\Git\rushstack\common\temp\pnpm-workspace.yaml` defines the workspace, and is discovered because the command is invoked with `common/temp` as the working directory.   (The relevant code is in [WorkspaceInstallManager.ts](https://github.com/microsoft/rushstack/blob/83001f419e191098e5137e047f5cbe478dc7de1d/apps/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts#L374).)

Having completed the installation, I would expect that I should be able to invoke `pnpm ls` or `pnpm outdated` like this (which is essentially the spec for this feature):
```shell
$ cd C:\Git\rushstack\common\temp
$ C:\Users\username\.rush\node-v14.15.3\pnpm-4.14.4\node_modules\.bin\pnpm install 
```

However, the command simply terminates without printing any error, no console output at all.  🤔  

@D4N14L any idea why  it doesn't work?

**Comment by octogonz** [comment]
I chatted with Daniel. He said that `pnpm install` originally had trouble discovering the `common/temp` workspace due to an issue that he fixed in PR https://github.com/pnpm/pnpm/pull/2532 .  So perhaps other PNPM commands have similar limitations?

I tried upgrading to PNPM 5.15.2 (since the RushStack repo was using 4.14.4).  With that change, `pnpm ls` now works.  (Hurray!)

@ksnyde could you try manually invoking the commands that you're interested in, and report back whether it does what you need?   

If so, then we have a complete dev plan:  Someone just needs to make a PR for Rush that adds the front-end described in https://github.com/microsoft/rushstack/issues/2347#issuecomment-725674120 for invoking the commands.

**Comment by D4N14L** [comment]
It's possible that there's some incompatibility with how we use PNPM vs. what PNPM expects, at least in those older versions of PNPM.

Regarding my PR that @octogonz shared, PNPM originally would not traverse out of the directory that the PNPM workspace file exists in when performing project discovery. I made a change to PNPM to make it assume that whatever the highest directory the PNPM workspace file traverses through would be the root of the repo, instead of the directory the workspace file exists in (ex. if a path to a project from the workspace file is `../../apps/myproject`, then `../../` would be the root of the repo). It's possible that this logic was only applicable to install, but has since been expanded to other commands in newer versions.

**Comment by isc30** [comment]
Any news about this? I'm unable to run basic commands like `pnpm why` in the repo

**Comment by octogonz** [comment]
Issue #2689 asked for `pnpm list`, which would also be solved by this same proposal.

We just need a volunteer to make the PR.

**Comment by octogonz** [comment]
https://github.com/microsoft/rushstack/issues/2378 asks for `pnpm link`

**Comment by octogonz** [comment]
https://github.com/microsoft/rushstack/issues/2766 asks for `pnpm why`

**Comment by octogonz** [comment]
In PR https://github.com/microsoft/rushstack/pull/2859, I took the approach of introducing a separate command `rush-pnpm` that simply passes along its arguments verbatim to the underlying PNPM command, but setting up the workspace context correctly, and doing validation to catch common mistakes.  

I'm proposing that this will be our generic escape hatch for accessing arbitrary PNPM features (e.g. `rush-pnpm outdated`), but then over time we will /also/ introduce corresponding Rush-implemented commands (e.g. `rush outdated`) that are specialized around Rush's particular model and features.

**Comment by chengcyber** [comment]
How about implementing this pnpm workspace command with a pluggable fashion. If we settle down the approach how rush plugin works. Then the pluign mode supports adding action to `RushCommandLineParser`. In that way, `rush pnpm` seems to be much easier to created with a plugin maybe named `RushPluginPnpmCommandProxy`. IMHO, it's better to create a new bin, because rush native functionality could be more reuseable.

**Comment by isc30** [comment]
hey, any news on this? `pnpm audit` would be nice too

**Comment by chengcyber** [comment]
recipes:

`cd` to your monorepo root dir and run:

- `pnpm audit -C common/temp`
- `pnpm why <package_name> -r -C common/temp`

**Comment by benjamind** [comment]
Does this pattern work for `pnp link`?

**Comment by buffcode** [comment]
In addition to [@chengcyber](https://github.com/microsoft/rushstack/issues/2347#issuecomment-1096974007):

To audit without installing any dependency (eg. a low-profile / early CI job), as `common/temp`  is only available after `rush install`:
```
# create empty package file
echo '{}' > common/config/rush/package.json

# run audit
pnpm audit -C common/config/rush
```

**Comment by majg0** [comment]
Any known existing way to deal with `pnpm outdated`?

**Comment by octogonz** [comment]
🚀The new `rush-pnpm` command is released with  `@microsoft/rush` 5.74.0.  

To use it:  Besides upgrading `rushVersion` in your **rush.json**, you need to add the `rush-pnpm` shell command by doing `npm install --global @microsoft/rush`.

**Comment by olivierlacan** [comment]
@chengcyber Which version of either pnpm or Rush did you use when testing out `pnpm why <package_name> -r -C common/temp`? 

I get no output:
```
rush-pnpm -v
6.7.1

rush -v
Rush Multi-Project Build Tool 5.97.1 - https://rushjs.io
```

Does this require a 7.x or 8.x pnpm?

**Comment by chengcyber** [comment]
@olivierlacan Nope. Currently, we are using pnpm@6. My guess is
1. run `rush update` first to get node modules installed
2. and then run `rush-pnpm why react` to see the output.
