### ISSUE TITLE
[rush] Add --check-only flag for install action

### ISSUE THREAD

**Issue by m1heng** [microsoft/rushstack#2570]
## Summary

we would like to check if the MR forgot to commit common/config/rush/pnpm-lock.yaml after change some deps in pacakge.json, which would certainly cause failure in our following CD where rush install is used. So a check command or a flag for install where only checks will be done without actual install will certainly help us save time in our CI.

## Details

Discussion in Zulip https://rushstack.zulipchat.com/#narrow/stream/262513-general/topic/install.20--check.20only

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| Would you consider contributing a PR? | Yes |

**Comment by m1heng** [comment]
A PR will be provided later next week

**Comment by iclanton** [comment]
@octogonz - Would it make sense for this to just be integrated into `rush change`?

**Comment by octogonz** [comment]
`rush change` normally performs validation that only applies to publishing.  It is optional in the sense that developers can get pretty far by running `rush install && rush build` while forgetting to do `rush change`.

Today `rush install` performs quite a lot of validation.  Not because it's related to installation, but rather because `rush install` is generally the first command that a person must run, and you MUST run `rush install` in order to build anything.  Therefore it's a good point in the workflow to catch problems.  Users probably already associate this validation with `rush install`, which would make `rush install --check-only` an intuitive design.

(For the purposes of CI, it might be useful to separate the operations so that their timings/success can be tracked individually.  For example maybe we introduce a `rush validate` that performs validation, and `rush install` performs installation, and then we would teach people that `rush install` automatically runs `rush validate`.  With such a design we would maybe then need `rush install --skip-validate` to avoid double-checking in CI -- not sure if that is actually an improvement.)

**Comment by m1heng** [comment]
I'm think adding a flag called validationOnly with will make install return before actual install will be executed.

```
// file: apps/rush-lib/src/logic/base/BaseInstallManager.ts
@@ -214,6 +219,11 @@ export abstract class BaseInstallManager {
         );
       }
 
+      if(this.options.validationOnly){
+        console.log('As validationOnly is specified and all validation have been passed, No actual install will be performed.');
+        return;
+      }
+
       // Delete the successful install file to indicate the install transaction has started
       this._commonTempInstallFlag.clear();
```

**Comment by wbern** [comment]
I don't know if this is directly related, but I've given people a custom command called `rush i` of global type that runs like `rush install || rush update`, because rush install seems to always be faster, it's "worth it for the validation to run before determining if rush install or rush update should be the script that runs.

If you added something like "rush validate" and "--skip-validate", I could make it slightly more performant, like (pseudo) `rush validate ? rush install --skip-validate : rush update`.
