### ISSUE TITLE
[rush] Rush changed projects, using git?

### ISSUE THREAD

**Issue by wbern** [microsoft/rushstack#2701]
## Summary
My org has started maintaining a small script that compares previous successful build's commit hash, with the current commit, and finds out changed rush projects in the diff that gets created. We recently found a use for this in a local commit hook as well, doing a diff between staged files and the last commit, because running "lint-staged" in 100 projects is unnecessary when you know which projects to run the lint step for (with --only parameter).

Just wondering what others recommend in this area? Is this functionality that actually exists within rush, without build cache? Our script is not big by any means, but would be cool to have a discussion about this, it seems like a very useful thing to have for commit hooks for example.

I will share the script on Monday when I'm back at work.

**Comment by iclanton** [comment]
I'd be interested in seeing the script.

We do something that sounds similar to verify Prettier formatting internally. @dmichon-msft wrote a simple tool for this that I think he's going to move to this (RushStack) repo. If the "run this tool on things that changed since XYZ ref" functionality seems useful for other things, we probably could build it directly in to Rush. It'd be interesting to get @dmichon-msft's thoughts on that as well.

**Comment by wbern** [comment]
@iclanton 

Since I don't have time to open-source this right now, I've created a gist in the interim. Would greatly appreciate your feedback, perhaps there are smarter way to do things with Rush.

https://gist.github.com/wbern/d0ffb116804b2c4bb61da10249500163

**Comment by dmichon-msft** [comment]
Looking at this gist, this would be more like implementing `rush build --since <refspec>`, i.e. what rush does in watch mode except initializing the baseline PackageChangeAnalyzer at `<refspec>`. Wouldn't be all that difficult to implement in BulkScriptAction.

Though for performance, it might make sense to use the same `git diff-index` strategy I used for the prettier hooks, since it's almost certainly faster than listing the full set of SHAs twice and comparing them in JavaScript. Instantiating PackageChangeAnalyzer has recently become much more expensive due to loading the rush-project.json files (up to a 3 seconds from previously <1 second) in the ignorer computation flow.

The one thing I'd want to add if this became a general feature, though, is diffing the lockfile to ensure that a project gets rebuilt if its installed dependency footprint changes, whether or not there were any accompanying code changes.

**Comment by wbern** [comment]
This script triggers all projects to be executed if pnpmfile has changed at all, so I'd say that's a good observation.

I'm not sure that I'd be able to contribute this to rush based on your description. 😅 But if it's not too hard to implement, one can hope that this issue can serve as a decent reference.
