### ISSUE TITLE
[rush] Update defaultBranch of repository to use "main" in rush.json

### ISSUE THREAD

**Issue by the-constant** [microsoft/rushstack#2788]
## Summary

As of rush@5.47.0, rush.json defaults to the branch of "master" for repository. Github and Gitlab have moved to the "main" branch as the default convention. Update Rush to follow the same convention.

This can easily be updated via [DEFAULT_BRANCH](https://github.com/microsoft/rushstack/blob/78aa5aded8051d9f38e8cf0d1513f20707edc54a/apps/rush-lib/src/api/RushConfiguration.ts#L39) however has the likelihood of causing regression issues for repos that:

- Do not have a defaultBranch of "master" specified AND
- Upgrade Rush to a newer version AND
- Do not change conventions to be in line with Git

  **Expected result:** 

  **Actual result:** 

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.47.0 |
| `rushVersion` from rush.json? | 5.47.0 |
| `useWorkspaces` from rush.json? | false |
| Operating system? | Windows |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 12.16.3 |

**Comment by elliot-nelson** [comment]
Azure DevOps default branch is now `main` as well.  The only big Git provider hold out is Bitbucket AFAIK.

That said, ideally we want Rush's defaults to be what _most Rush users_ would need out of the box, and Rush users tend to lean bigcorp, where development trends take longer to take hold.

My vote would be to include the change from `master` to `main` with a batch of other "get up to speed" bumps, like pushing node from 12.x to 14.x, and release them together -- possibly as Rush 6.x?

**Comment by octogonz** [comment]
Just to clarify, this request was regarding the `rush init` template, correct?  

I'd support:
- Changing the `rush init` default from `master` to `main`
- Updating the `rush init`  setting for `nodeSupportedVersionRange` to include 16.x which is now LTS.  (The [NodeJsCompatibility.ts](https://github.com/iclanton/rushstack/blob/master/apps/rush-lib/src/logic/NodeJsCompatibility.ts) checks were already updated in https://github.com/microsoft/rushstack/pull/2993).)
- We can also get with the times and rename `master` -> `main` in the Rush Stack repos, although it might be useful to preserve at least one repo on `master` just to validate that it is still supported. (https://github.com/microsoft/rush-example ?)

BTW note that Node.js recently moved to keeping [three versions in LTS](https://github.com/nodejs/Release) instead of two.  That is why this repo validates 3 different versions:

https://github.com/microsoft/rushstack/blob/9d7063580236f776364e024dcc8d35d6044d7c31/rush.json#L127

Should the  `rush init` template use the same default?  Or should it be more conservative?

> possibly as Rush 6.x?

Bumping to Rush 6 would be about breaking changes such as retiring deprecated features.  Updating the `rush init` template is fine as a minor version bump.

**Comment by brandonthomas** [comment]
In addition to this, can we include updating `rush change` to default to `main`? As stated, that's where things are trending. I think it would be reasonable to detect if a `master` branch exists, and if not, look for `main` or vice versa to prevent a breaking change with this specific command.

**Comment by elliot-nelson** [comment]
✅ All default branch references in Rush now use `main` (it can be overridden back to `master` for legacy monorepos).
