### ISSUE TITLE
[heft] Jest presets such as "react-native" can't be loaded by a rig

### ISSUE THREAD

**Issue by JerryMacedoCastro** [microsoft/rushstack#2794]
Hello! I'm trying to use a rig package to centralize jest configurations file following this [docs](https://rushstack.io/pages/heft_tasks/jest/) 

I created a `jest.config.js file` in the rig package  
```
{
  "extends": "react-native",
  "silent": false,
  "verbose": false,
  "rootDir": "../",
  "roots": ["<rootDir>", "<rootDir>/src"],
  "testURL": "http://localhost/",
  "testMatch": ["<rootDir>/src/**/*.test.{ts,tsx}"],
  "testPathIgnorePatterns": ["/node_modules/"],
  "collectCoverage": false,
  "coverageDirectory": "<rootDir>/temp/coverage",
  "collectCoverageFrom": [
    "src/**/*.{ts,tsx}",
    "!src/**/*.d.ts",
    "!src/**/*.test.{ts,tsx}",
    "!src/**/test/**",
    "!src/**/__tests__/**",
    "!src/**/__fixtures__/**",
    "!src/**/__mocks__/**"
  ],
  "coveragePathIgnorePatterns": ["/node_modules/"],
  "transform": {
    "^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js",
    "\\.(jsx|ts|tsx)$": "babel-jest"
  },
  "transformIgnorePatterns": [],
  "setupFiles": [
    "<rootDir>/jest-setup.js",
    "<rootDir>/node_modules/react-native-gesture-handler/jestSetup.js",
    "@rushstack/heft/lib/exports/jest-global-setup.js"
  ],
  "resolver": "@rushstack/heft/lib/exports/jest-improved-resolver.js",
  "setupFilesAfterEnv": ["@testing-library/jest-native/extend-expect", 
    "<rootDir>/jest-setup.js"]
}
```

 and create a reference for it in the app I'm want to test with: 
` 
{
  "extends": "@myPackage/profiles/app/config/jest.config.json"
}
`
When I run the teste I'm getting the error:  

![image](https://user-images.githubusercontent.com/39466788/124805673-3249fa80-df32-11eb-92b5-3fe07d1c8213.png)

The tests are ok with I let the jest config at the app i'm want to test. 

I added the `heft-jest-plugin` at `heft.json`. 

| Question | Answer |
| -------- | -------- |
|`react-native`version? | 0.64.1 |
| `@rushstack/heft` version? |   0.34.3 |
| Operating system? | Windows  |
| `Node.js` version ? |  v14.17.0 |

**Comment by octogonz** [comment]
> I created a `jest.config.js file` in the rig package

In our monorepo, I think we would prefer to block people from doing this. Jest configurations should be a simple, readable data object. "Configuration" should not be a computer program coded in unsafe JavaScript that requires careful analysis to deduce what your configuration is, and which can potentially change based on nondeterministic inputs.

I understand that for certain awkward cases, replacing `jest.config.json` with `jest.config.js` might be more expedient than other options (for example, a prebuild step that generates `jest.config.json`).  But is there a way we could make this opt-in rather than available-by-default?

**Comment by octogonz** [comment]
> > I created a `jest.config.js file` in the rig package
> 
> In our monorepo, I think we would prefer to block people from doing this.

\* We realized that this was a typo -- @JerryMacedoCastro's example file is actually `jest.config.json`.  The "Unexpected token" error is coming from the `react-native` NPM package.

In other words, this issue boils down to:

In the new default mode where `disableConfigurationModuleResolution=false`:
- Jest configuration can be loaded using rigs
- But Jest preset NPM packages such as `react-native` are not supported (because `"extends"` can't load them, and `"preset"` is not allowed)

In legacy mode where `disableConfigurationModuleResolution=true`:
- Jest preset NPM packages such as `react-native` are supported 
- But Jest configuration is not riggable

**Comment by octogonz** [comment]
PR https://github.com/microsoft/rushstack/pull/2882 implements a solution for loading load presets, but it needs some rails to avoid unwise configurartions. @D4N14L and I discussed the design today and came up with this:

### 1. The `"preset"` JSON field must be an NPM package name (instead of something like `./path/to/file.js`).

Heft will resolve the package name and pass the absolute path to Jest.

Rationale: `"preset"` is not meant to be an escape hatch for generating configurations using ad hoc JavaScript scripts

### 2. If the `"preset"` field appears in a file, then the `"extends"` field must NOT be used in that file.

For example, it's okay to have this:
```
A --["extends"]--> B --["extends"]--> C --["preset"]--> D --["preset"]--> E

(Heft resolves A->B->C, and then Jest resolves D->E)
```

But it's NOT OKAY to have multiple inheritance like this:
```
A --["extends"]--> B --["extends"]--> C 
                    --["preset"]--> D

(i.e. B inherits settings from both C and D)
```

### 3. Heft needs special logic to resolve `"preset"`

The [Jest docs](https://jestjs.io/docs/configuration#preset-string) stipulate that `"preset": "x"` is resolved by first doing NPM resolution on `x`, and then looking for a file `jest-preset.*` in that folder, and then this file is interpreted as a Jest config file.

In order to support rigs, Heft needs to resolve `x` to something like `../node_modules/x/jest-preset.json` and then pass that absolute path to Jest. Maybe we can reuse a Jest API.

If `jest-preset.json` includes resolved references, it's up to Jest to correctly resolve those from the rig package folder, instead of the root project folder.  It's TBD how well  Jest will handle that.

**Comment by JerryMacedoCastro** [comment]
Is there something I can do to help you guys? I'll be glad since this is an important task for my team.
