### ISSUE TITLE
[rush] Both incremental build and build cache are not working for this project structure

### ISSUE THREAD

**Issue by davidabap** [microsoft/rushstack#2874]
## Summary
Incremental build working fine in our project previously, but it doesn't work since we bump to `rush 5.50.0` I change a little in your demo project and the issue can be reproduced. https://github.com/davidabap/rush-example
In a word, I put your demo project into `inner` folder and introduce a new my-app2 which located in the `outer` folder

## Repro steps

1. Run `rush update` in inner
2. Run `rush build` in inner * 2
3. Incremental build doesn't work
4. Delete my-app2 in `rush.json`
5. Run `rush build` in inner * 2
6. Incremental build working fine

  **Expected result:** 
Incremental build and build cache should working for this rush project sturcture like before.
  **Actual result:** 
Both Incremental build and build cache are not working 
## Details
You can find the undefined error in the `rush build --verbose` mode, the issue come from https://github.com/microsoft/rushstack/blob/master/apps/rush-lib/src/logic/ProjectChangeAnalyzer.ts#L243
![image](https://user-images.githubusercontent.com/25033055/130891490-fc298ddf-c248-4cb8-a435-5f6fd0bea363.png)

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.52.0 |
| `rushVersion` from rush.json? | 5.52.0 |
| `useWorkspaces` from rush.json? | false |
| Operating system? | Mac |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | 16.3.0 |

**Comment by davidabap** [comment]
Hi @iclanton @dmichon-msft  is there any comments on that ? Is it some regression which will be fixed in new patch ? or Rush doesn't support "**project exists outside of rush.json parent folder**" ?

**Comment by elliot-nelson** [comment]
Hi @davidabap!

I was looking into your issue with the folder structure above and I notice that as of https://github.com/microsoft/rushstack/pull/2838, the behavior of your situation has changed:

Instead of emitting an error/warning, it now succeeds, but the _outer_ app is actually not checked for changes.  This means the result is actually a false success -- no matter how many changes you've made to the outer app, `rush build` will never attempt to rebuild it.  (It incorrectly believes it has a "cache hit" and just restores from cache.)

The main issue is that `rush.json` is [expected to be in the root of your repo](https://rushjs.io/pages/configs/rush_json/), and projects located at `"../"` are _not supported_.  Because it's not supported, it's easy for changes over time to keep breaking this folder structure in various ways (it looks like in this thread, it was "broken" in three different ways over time).

To avoid confusion, we should probably make an explicit implementation change and exit with an error if any project is detected in `rush.json` outside the `rush.json` parent folder.

I suppose we could also support projects outside the parent folder, but inside the git repo, but as soon as you open up the door to `"../"`, you could potentially be multiple levels outside of the git repo, making incremental build checking impossible.  I think the safest thing to do is just inform the user they cannot have projects outside the parent folder.

**Comment by davidabap** [comment]
Hi @elliot-nelson, for my project structure case, it's huge and complex, not easy to adjust in short time. Is is possible to only give a 'soft warning' but not 'exit with an error' ?

**Comment by elliot-nelson** [comment]
Given the current state of `master` branch, just waiting for the next release will likely give you what you want -- the build won't really behave "correctly", but your CI would at least build without errors.

I've also put up a potential PR to fix the incremental build for that scenario so it's officially supported, we'll see what David + Ian think.
