### ISSUE TITLE
[rush] Is "Incremental update" available?

### ISSUE THREAD

**Issue by a20185** [microsoft/rushstack#3102]
## Summary

I was using rush to manage monorepo, my monorepo has a bunch of apps (tens of apps, in general).
Hence, the project cost a lot of time on linking (aka, `rush update`) after a simple dependency was added to the project, precisely it  was 3~5 minutes per new dependency add.

## Details

However, in most occasions, our monorepo app was mostly independent to each other, except sharing some contents from a common shared app. Therefore I was wonder, if rush can provide an "incremental method" for updating or linking dependencies on demand:
- If the new dependency was only affect current app, then just update current app.
- Otherwise follow by dependency graph, update all bundles just occurs in the dependency graph (instead of all apps).

Maybe an `option` in `rush update` will be available? We can call it manually if it's possible

```shell
rush add -p xxxx -s
rush update --scope=targetApp 
```

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.54.0 |
| `rushVersion` from rush.json? | 5.54.0 |
| `useWorkspaces` from rush.json? | true |
| Operating system? | macOS Catalina |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | V16.0.0 |

**Comment by Faithfinder** [comment]
`rush install` with pnpm and `useWorkspaces` supports `--to` and other selectors similar to `build`

**Comment by ISFhr** [comment]
When add a package in a repo , rush will run update command finally, it will check all the repo in my monorepo project. But most times I can make sure just a single repo need update. So will update command add a parameter like '-t' in rush build command?
Because I still think udpate is little slowly, only update single is more fast.

like
rush add -p lodash -t @my/repo

In addition，is there some best-practices can make the time of dependence install more efficient？Update command always make me waiting before my terminal or in CI.(I prefer enjoy the fast of pnpm add, just linking no update)

**Comment by D4N14L** [comment]
Scoped installs and incremental updates are two separate concepts. It sounds like you're more referring to the latter in this case. 

`rush update --to <package>` wouldn't work in the way you want, since that would produce a lockfile updated to only include the updated values in the packages within the scope of the update, removing all other packages. This is why we only allow it for `rush install`, and then mark the install as "dirty" since it's not a full install anymore. What you're more looking for is likely what @ISFhr is requesting, which is to incrementally add a package when running `rush add` instead of adding and running a full update.

I believe this could possibly be accomplished by implementing `pnpm add ...` when doing `rush add ...` for the PNPM case (instead of calling the full `rush update` code as we currently do), however I don't have the bandwidth to implement this myself. If another dev would like to add this feature, I could absolutely review it and assist on getting this merged.

**Comment by elliot-nelson** [comment]
As issue #3110 tracks the "rush update --to" feature request, closing this in favor of that ticket.
