### ISSUE TITLE
[rush] see files that git ignored as none source file

### ISSUE THREAD

**Issue by deepkolos** [microsoft/rushstack#3117]
## Summary

some project does't have one `dist` or `lib` dir as output dir, it may output file in place. for example `wechat miniprogram`

so `projectOutputFolderNames` is not well enough to describe this scene, but `.gitignore` can

![image](https://user-images.githubusercontent.com/12824616/147624174-d2697f6c-ea70-4761-b04f-8a6f58ae91ed.png)

## Repro steps

  **Expected result:** 

  **Actual result:** 

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? |  |
| `rushVersion` from rush.json? |  |
| `useWorkspaces` from rush.json? |  |
| Operating system? |  |
| Would you consider contributing a PR? |  |
| Node.js version (`node -v`)? |  |

**Comment by iclanton** [comment]
This isn't something that our build cache currently supports. The build cache only supports folder names due to ease of cleaning outputs before restoring from cache. The best option would be to configure TypeScript to output into a separate folder from the source files.

If this is a feature that you need, and you would be willing to implement it, we would probably be willing to accept that change.

In the meantime, you can disable the build cache for individual projects via the `config/rush-project.json` file.
