### ISSUE TITLE
[rush][bug] local-only cache is never written

### ISSUE THREAD

**Issue by isc30** [microsoft/rushstack#3242]
## Summary

For some reason, `isCacheWriteAllowed` from `ShellOperationRunner` is always false even for `local-only`.

I've been able to debug rush-lib up to this line, where the value is always `false`: https://github.com/microsoft/rushstack/blob/2017049bab91d1a5426d98e65babcc2c233a44e6/apps/rush-lib/src/logic/operations/ShellOperationRunner.ts#L371

## Repro steps

`build-cache.json`
```
"buildCacheEnabled": true,
"cacheProvider": "local-only"
```

`experiments.json`
```
"usePnpmFrozenLockfileForRushInstall": true,
"usePnpmPreferFrozenLockfileForRushUpdate": true,
"omitImportersFromPreventManualShrinkwrapChanges": true,
"buildCacheWithAllowWarningsInSuccessfulBuild": true,
"phasedCommands": true
```

my project specific `rush-project.json`
```
{
  "$schema": "https://developer.microsoft.com/json-schemas/rush/v5/rush-project.schema.json",
  "incrementalBuildIgnoredGlobs": ["temp/**", "dist/**", "etc/**"],
  "operationSettings": [
    {
      "operationName": "build",
      "outputFolderNames": ["dist", "etc"]
    }
  ]
}
```

and then running `rush build`

## Hacking the code to get it working
If I get rid of the condition on this line, everything works as expected so there must be something setting it as `false` incorrectly.

https://github.com/microsoft/rushstack/blob/2017049bab91d1a5426d98e65babcc2c233a44e6/apps/rush-lib/src/logic/operations/ShellOperationRunner.ts#L371

  **Expected result:** 

The build gets cached properly

  **Actual result:** 

The build doesn't even try to get cached

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | latest |
| `rushVersion` from rush.json? | latest |
| `useWorkspaces` from rush.json? | true |
| Operating system? | Windows / Linux |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | LTS |

**Comment by isc30** [comment]
I think the value itself is correct but its caused by using `--only`

**Comment by dmichon-msft** [comment]
The designed behavior of `isCacheWriteAllowed` is that it is true if and only if:
1) The currently executing command contains all dependencies of the specified operation
2) The specific operation defines the outputFolderNames field to allow caching
3) Caching is not disabled in command-line.json
4) Caching is enabled globally

This means that, for example, if you have two projects, `A` and `B`, with `B` depends on `A` (and all cache options configured and enabled), then:
- Running `rush build` will build both `A` and `B`, and write cache entries for both
- Running `rush build --only A` will build `A` and, since all dependencies of `A` are part of the build (it has none) write the cache entry for `A`
- Running `rush build --only B` will build `B`, but, since it cannot guarantee the state of `A`, which is a dependency, will *not* write a cache entry for `B`, since you might have locally modified the outputs of `A` in a manner that affects the outputs of `B` and cannot be detected by the analysis that generates the cache key.

I am open to defining a build flag to indicate that "I, the developer, hereby acknowledge that writing a cache entry from this project may corrupt my local cache with incorrect output, please do it anyway" but it cannot be the default because it's very painful for a developer to debug when a fresh build works but replaying from cache does not.

**Comment by isc30** [comment]
Thanks for the awesome explanation! Its all clear and I think this is the best way of doing it, perfect balance between getting cached builds and ensuring nothing gets corrupted.

I wouldn't even introduce a flag to override that, it could cause more trouble than help.

I see some points that could be improved:
- when a project doesn't write to cache and cache is enabled, show a verbose message saying: project `B` depends on `A` but `A` isn't part of the current build. The build cache will not be written as it could be corrupt.
- use `allowWarningsInSuccessfulBuild` from `command-line.json` instead of the custom `buildCacheWithAllowWarningsInSuccessfulBuild`. It took me some time debugging what was going on until I discovered this existed 😄 
- documentation

Let me know what you think! thanks!

**Comment by GongT** [comment]
I have this issue too, it never try to create "temp/build-cache" folder

<details>
<summary>Log</summary>

```
==[ @build-script/rollup-plugin-module-import-dew ]===============[ 6 of 31 ]==

This project was not found in the build cache.

Invoking: tsc -p src 

"@build-script/rollup-plugin-module-import-dew" completed successfully in 1.67 seconds.

==[ @idlebox/node-json-edit ]=====================================[ 7 of 31 ]==

This project was not found in the build cache.

Invoking: scripts/build.sh 

run ttsc...
create .d.ts file...
Done.
"@idlebox/node-json-edit" completed successfully in 8.08 seconds.

==[ @build-script/typescript-transformer-import-commonjs ]========[ 8 of 31 ]==

This project was not found in the build cache.

Invoking: ttsc -p src 

"@build-script/typescript-transformer-import-commonjs" completed successfully in 6.51 seconds.
```

</details>

**Comment by MichaelSitter** [comment]
Can confirm what @GongT is seeing, using the `local-only` cache provider the build cache is never getting written. I'm using rush@5.63.0, all my packages have `rush-project.json` defined or are rigged. Caching is not disabled in command-line.json.

build-cache.json:
```
  "buildCacheEnabled": true,
  "cacheProvider": "local-only"
```

experiments.json
```
"buildCacheWithAllowWarningsInSuccessfulBuild": true
```
