### ISSUE TITLE
[api-documenter] Breaking change in YamlDocumenter yaml emit to support DocFX 3

### ISSUE THREAD

**Issue by rbuckton** [microsoft/rushstack#3268]
## Summary

#2382 made a breaking change to the YAML emit to support DocFX 3, however DocFX 3 is still in beta, and the latest stable release is still 2.59 which does not support this new SDP format. There is also no mechanism to revert to the old behavior aside from [runtime patching](https://github.com/esfx/esfx/blob/main/scripts/docs/patches/api-documenter/disableConvertToSDP.js) or forking the repository (which isn't a viable long-term solution).

## Repro steps

Run api-documenter against a js/ts project targeting DocFX 2

## Details

I am using DocFX 2.57 with a custom template that leveraged the previous emit behavior.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/api-documenter` version? | 7.15.3 |
| Operating system? | Windows |
| Documentation target? | DocFX (YAML) |
| Would you consider contributing a PR? | Maybe (time permitting) |
| TypeScript compiler version? | 4.5 |
| Node.js version (`node -v`)? | 16.6.2 |

**Comment by asimontsev** [comment]
@rbuckton the same problem stops us from using the api-documenter as well. However, when I was exploring the source code, I realized that the fix should be quite trivial, that's why I took a liberty to create a pull request - it adds a new flag to the CLI which allows for choosing between UDP and SDP YAML formats. Hopefully, maintainers will accept it and publish update in npm.

**Comment by octogonz** [comment]
Awesome, thanks @asimontsev  for fixing this!  Your PR is released with `@microsoft/api-documenter` 7.16.0
