### ISSUE TITLE
[eslint-config] feature-request: expose `buildConfig` with optional overrides

### ISSUE THREAD

**Issue by prescience-data** [microsoft/rushstack#3384]
## Reference
https://github.com/microsoft/rushstack/blob/20aaae95c72a014dedc6f93a94ca224074aa888c/eslint/eslint-config/profile/_common.js#L25

 ## Summary

It would be nice to be able to call `buildConfig(<profile>, <overrides>)` directly to generate custom a eslint config in rigging.

This (from what I understand) would remove the need to have `@rushstack/eslint-config` as a local dependency on every package in order to use things like `@rushstack/eslint-config/patch/modern-module-resolution` ?

## Details

The modification could look something like 
```js
function buildRules(profile, overrides = {}) { 
  const rules = {
    // ...current rule builder
  }

  return someDeepMergeLogic(rules, overrides)

}
```

Then in the local monorepo's eslint rigging could use something like

```js
// Not sure if this is still required in this context?
require("@rushstack/eslint-config/patch/modern-module-resolution")

const when = (env) => (process.env.NODE_ENV === env ? "error" : "off")


const { buildRules } from "@rushstack/eslint-config/patch/builder"

module.exports = buildRules("web-app", {
  plugins: ["simple-import-sort", "prefer-arrow"],
  "@typescript-eslint/no-floating-promises": when("test"),
  "@typescript-eslint/naming-convention": [
      "warn",
      {
        selector: "interface",
        format: ["PascalCase"],
        custom: {
          regex: "^I[A-Z]",
          match: false
        }
   }
})

```

**Comment by D4N14L** [comment]
Unfortunately, exposing the `buildConfig` method to .eslintrc.js won't solve the goal of removing `@rushstack/eslint-config`. It will only provide you the default configuration, but you will then have to satisfy the dependencies within. The way the patch works is to load up and tweak ESLint in order to resolve modules relative to the module that declared their use. What this would mean is that you would not only need to have `@rushstack/eslint-config` as a dependency for the project, but you would also need to have all the packages that were referenced in that config.

What you're looking for is something more along the lines of my PR here: #3020 

What my PR does is allow you to `extend` from packages that don't contain the `eslint-config` postfix in their name, which is a limitation of ESLint. Once that is possible, you can then provide ESLint shareable configs in rigs that can be used by any consuming project (with a few caveats, which I go into more detail on over here: #3021)

**Comment by prescience-data** [comment]
oh wow : 
> _from packages that don't contain the eslint-config postfix in their name, which is a limitation of ESLint_

just spent a day or so trying to work out why linting was working in one Rush monorepo I have but not another and this is the reason. 🤦‍♂️ 

_(one was published as `@domain/eslint-config` and the new one I tried to be tricky and stick all my lint configs (eg `postcss`, `stylelint`, etc) in the same `@domain/linting` package)_

Thanks for that context, will revert to the "normal" way (ie separate `eslint-config` package and extend the `rush` configs locally.
