### ISSUE TITLE
[rush] Add shamefully-hoist to pnpm options

### ISSUE THREAD

**Issue by glopezep** [microsoft/rushstack#3569]
## Summary

Just add shamefully-hoist option when run pnpm install, it's required for some packages

## Repro steps

  **Expected result:** 

  **Actual result:** 

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? |  |
| `rushVersion` from rush.json? |  |
| `useWorkspaces` from rush.json? |  |
| Operating system? |  |
| Would you consider contributing a PR? |  |
| Node.js version (`node -v`)? |  |

**Comment by iclanton** [comment]
This would break the standboxing behavior of PNPM if we added it by default. If you need this for your repo, you can set this option in your `.npmrc`: https://pnpm.io/npmrc#shamefully-hoist. Keep in mind that this may cause unexpected behavior and effectively disables PNPMs package isolation system.

**Comment by glopezep** [comment]
@iclanton for some reason when using .npmrc it doesn't work

**Comment by octogonz** [comment]
@glopezep Hoisting is a quick hack for some problems.  But in a large monorepo, hoisting causes [much worse trouble](https://rushjs.io/pages/advanced/phantom_deps/) -- it is best to fix the root cause using proper methods such as `pnpmfile.cjs`. See https://github.com/microsoft/rushstack/issues/3542 and specifically https://github.com/microsoft/rushstack/issues/3542#issuecomment-1188595580 for a narrowly applied version of hoisting that would minimize some of the trouble.

**Comment by octogonz** [comment]
> for some reason when using .npmrc it doesn't work

You have to use `common/config/rush/.npmrc`.
