### ISSUE TITLE
[rush] Having nextBump defined, the command rush change does not ask the type of changes done

### ISSUE THREAD

**Issue by jmattiet** [microsoft/rushstack#3595]
## Summary

The command "rush change" does not ask for the type of changes i've done if the nextBump attribute within the versionPolicy is defined.

## Repro steps

Define a lockStepVersion policy.
Define the attribute nextBump with any value (patch, minor, major...)
Do any change on your code.
Run the command "rush change" to update the changelog.

  **Expected result:** Should be requested the type of changes done (major, minor, patch...) and the description as well.

  **Actual result:** Only the description is requested.

## Details

If i remove the attribute "nextBump" the rush change command works fine.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.76.1 |
| `rushVersion` from rush.json? | 5.76.1 |
| `useWorkspaces` from rush.json? | Yes |
| Operating system? | Mac |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | 14.19.0 |

**Comment by iclanton** [comment]
This is by design. The issue that added the "no nextBump required" feature is here: https://github.com/microsoft/rushstack/issues/3047

This is a relic of the old design of the lockSteppedVersion feature. There has been a plan to completely redesign version bumping and publishing for a while now, but it hasn't been a priority.
