### ISSUE TITLE
[rush] rush publish doesn't work correctly

### ISSUE THREAD

**Issue by LucasZheng** [microsoft/rushstack#3679]
I create a new rush monorepo project follow the official document and want to publish a package to npm. After I execute `rush publish -p --include-all`, it shows:
```
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/xx-xx-xx  - Not found
npm ERR! 404  'xx-xx-xx@1.0.5' is not in this registry.
```
but when I execute `npm publish --otp=xxx` under the package scope, the package 'xx-xx-xx@1.0.5' was published successfully to npm.
Any suggestions will be appreciated.

**Comment by iclanton** [comment]
This is the same issue mentioned here: https://github.com/microsoft/rushstack/issues/3680

`rush publish` is currently designed to use NPM access tokens instead of username+password authentication (see here https://docs.npmjs.com/about-access-tokens), but that is more of an enterprise-grade feature.

**Comment by iclanton** [comment]
Closing this as duplicate.
