### ISSUE TITLE
[rush] `incrementalBuildIgnoreGlobs` (in rush-project.json) does not like globs that start with periods `.`

### ISSUE THREAD

**Issue by jessekrubin** [microsoft/rushstack#3721]
Using nextjs the default build output is a dir called `.next`

The `.next/cache` dir can become quite large. 

If  add ` ".next/cache/**"` to my `incrementalBuildIgnoreGlobs` arr the files under the cache dir are NOT ignored. 

If change my build output to be `next` (no period) and instead add ` "next/cache/**"` to my `incrementalBuildIgnoreGlobs` arr the build cache seemingly ignores the files under `next/cache/**`

**Comment by elliot-nelson** [comment]
Out of curiousity, what problem is the setting you are adding solving?

I would expect the .next/cache folder to be gitignore'd already, and you don't need to ignore files that aren't tracked by git.

(wondering if maybe this is a special case)

**Comment by jessekrubin** [comment]
@elliot-nelson Well the behavior IS inconsistent, but the use case if you are curious is being able to push and pull build-caches to using rush's local build-cache and github-actions-cache.

I also do not understand your point about ignoring files that aren't tracked by git. my `dist` dirs of other build outputs are not tracked by git but rush's local-build-cache picks them up and does excellent caching with them.

**Comment by elliot-nelson** [comment]
Ah I see the issue -- the `incrementalBuildIgnoreGlobs` property is not used to control what files to cache, it's only used to control _build inputs_.

For example, if you add `incrementalBuildIgnoredGlobs: ['vendor-art/**']` to your rush-project, it means that if someone checks in changes to the `vendor-art` folder, it will be considered a "no-op" by the build cache -- this project's hash value will not change.

It doesn't mean anything to point `incrementalBuildIgnoredGlobs` at a build output folder, because that folder is already gitignore'd. E.g., in your monorepo root .gitignore it probably says this:

```text
# nextjs output
.next
```

(That said, it's quite concerning that Next is putting its _cache output_ in the same folder as its _build output_ -- that is not a structure Rush build cache is really designed for. I wonder if there's some way to configure that differently 🤔)

**Comment by iclanton** [comment]
>(That said, it's quite concerning that Next is putting its cache output in the same folder as its build output -- that is not a structure Rush build cache is really designed for. I wonder if there's some way to configure that differently 🤔)

Yeah, sounds like that's the underlying problem. We've talked about adding support for more granular cache entry inclusion patterns, but that comes with perf implications.

It doesn't look like NextJS supports configurating that folder (see issue https://github.com/vercel/next.js/issues/10111), but that would probably be your next best bet.

I think we'd be willing to explore more granular caching semantics, though.
