### ISSUE TITLE
[rush] phased command not work correct with upstream

### ISSUE THREAD

**Issue by yoyo930021** [microsoft/rushstack#3753]
## Summary

I want to have a command for run upstream project build and self project lint without self project build.
But when I try to set it, I only get a command for for run upstream project build and self project lint and self project build.

## Repro steps

Clone this project: https://github.com/yoyo930021/rush-upstream-phase-bug
```bash
rush install
rush lint
```

  **Expected result:** 
  only run 3 operations
  project (lint)
  upstream (build)
  upstream (lint)

  **Actual result:** 
  run 4 operations
  project (lint)
  upstream (build)
  upstream (lint)
  project (build)

## Details

In this line, project will add any phase with selection project.
https://github.com/microsoft/rushstack/blob/main/libraries/rush-lib/src/logic/operations/PhasedOperationPlugin.ts#L40

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.83.3 |
| `rushVersion` from rush.json? | 5.83.3 |
| `useWorkspaces` from rush.json? | true |
| Operating system? | Mac |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 16.16.0 |

**Comment by dmichon-msft** [comment]
This is a change to the specification of how phased commands work. The current design is:
1) Rush evaluates the set of phases that are involved in your command in isolation to detect the full set of phases to include
2) Rush evaluates the set of projects in isolation to determine the full set of projects to include
3) For all selected projects, Rush includes all selected phases in the build graph

The ask here is to have `rush test` run `_phase:test` in all selected projects and do whatever minimal set of supporting operations are necessary to make that happen.

There's a further level of redesign I've been considering which is to be able to ask Rush to run `_phase:test` in a specified target project, and do all necessary supporting operations to make that happen. Ultimately the problem comes down to that phase selection is performed by the command definition, and the command line only allows selecting projects, we don't have a CLI mechanism to specify both target phases and target projects.

**Comment by yoyo930021** [comment]
Do we have full specification of this? I only see document and https://github.com/microsoft/rushstack/issues/2300 .
I literally think that the current behavior is unreasonable.

```
{
  "commandKind": "phased",
  "name": "test",
  "phases": ["_phase:build", "_phase:test"],
}
```
When we use `rush test` command, we choose two "_phase:build", "_phase:test" phase, the dependency is not my chosen.
But the https://github.com/microsoft/rushstack/blob/main/libraries/rush-lib/src/logic/operations/PhasedOperationPlugin.ts#L75-L81 more like a white list of phase.
