### ISSUE TITLE
[rush] Execute a shell command in scope of a project.

### ISSUE THREAD

**Issue by chengcyber** [microsoft/rushstack#3819]
## Summary

This is a feature request in Rush.js. Comparing with lerna or pnpm, they provides a command to execute shell command in scope of a project.

Lerna:

doc: https://github.com/lerna/lerna/blob/main/commands/exec/README.md

```
$ lerna exec -- <command> [..args] # runs the command in all packages
$ lerna exec -- rm -rf ./node_modules
$ lerna exec -- protractor conf.js
$ lerna exec -- npm view \$LERNA_PACKAGE_NAME
$ lerna exec -- node \$LERNA_ROOT_PATH/scripts/some-script.js
$ lerna exec --scope my-component -- ls -la
```

pnpm:

doc: https://pnpm.io/cli/exec

```
pnpm -r exec rm -rf node_modules
pnpm -r exec jest
pnpm -r exec jest --filter "app..."
```

This makes me think is it possible to archive the same thing in Rush.js.

## Possible solutions

Option 1:

Implement a `rush exec` command, with the help of custom remainder feature by https://github.com/microsoft/rushstack/pull/3776.

The user story would be

```
rush exec --to my-app -- rm -rf node_modules
rush exec --to my-app -- node $RUSH_REPO_ROOT/scripts/migration.js
```

Option 2:

Because Rush.js has already bulk/phased script action, it will be better to support specifying "shellCommand" for bulk or phased scripts, or maybe a new script type (?) something like:

```
{
  "commands": [
    {
      "name": "migration",
      "commandKind": "???",
      "shellCommand": "node $RUSH_REPO_ROOT/scripts/migration",
      ....
    }
  ]
}
```

The user story would be 

```
rush migration --to my-app
```

**Comment by D4N14L** [comment]
I have no issue with this in general, seems like it would be useful. Option 2 seems to make more sense in the context of bulk/phased script commands, where the `shellCommand` field is a fallback command for when the project doesn't specify a `migration` script, when the `shellCommand` field is undefined, it falls back to existing behavior.

For Option 1, I feel like that adds a lot of flexibility for quickly writing cleanup scripts or validating information across projects. Both seem useful. @iclanton / @octogonz thoughts?

**Comment by sherlockfeng** [comment]
implement Option 2 in this [pr](https://github.com/microsoft/rushstack/pull/3862)

**Comment by octogonz** [comment]
I agree with the consensus from above. A couple additional comments:

- **Supporting autoinstallers is important:** It's uncommon that an operation can be fully implemented as a standalone `.js` without depending on any NPM package. (Even if the operation could be implemented using the shell, we have problems that Windows/Mac/Unix have inconsistent availability of shells and their supporting tools. Often `.js` is the most portable way to implement logic.)

- **We could also consider introducing an "autobuilder" mode:** Instead of autoinstalling, maybe some commands could work by running `rush install --to x && rush build --to x` and then invoking a script from project `x`. Just an idea.
