### ISSUE TITLE
[rush] How to bundle a tool that accesses internal APIs from rush-lib

### ISSUE THREAD

**Issue by StarFishing** [microsoft/rushstack#3895]
@microsoft/rush-lib/lib/logic/pnpm/PnpmfileShim require ` pnpmfileSettings.json` ,but don't have this file
## Summary

https://github.com/microsoft/rushstack/blob/main/libraries/rush-lib/src/logic/pnpm/PnpmfileShim.ts#L42

## Repro steps
install @microsoft/rush-lib
import api from @microsoft/rush-lib
esbuild src/index.ts --platform=node --target=node16  --bundle   --outfile=bootstrap.js

  **Expected result:** 
 build success
  **Actual result:** 
[ERROR] Could not resolve "./pnpmfileSettings.json"-
## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| Package name: |@rushstack/the-package-name  |
| Package version? | ~5.86.0  |
| Operating system? |  Mac  |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | 16.18.0- |

**Comment by StarFishing** [comment]
@rushstack/rush-sdk cant't meet my needs. 
I want to use some basic api to meet some customized scenes，such as 
 `import { ChangeFile } from '@microsoft/rush-lib/lib/api/ChangeFile'`
this api is not export by `rush-sdk`.There are many other kinds of api. so I want `@rushstack/rush-sdk ` have same file with `rush-lib` and resolve build problem. or `rush-lib ` be compatible with esbuild

**Comment by iclanton** [comment]
Do you need to bundle `rush-lib`, or can you leave it as an external from your bundle, `require`'d from the `node_modules` folder? `rush-lib` isn't really intended to be bundled by other tools.

We could stick a dummy `pnpmfileSettings.json` file in there to fix this specific scenario, but I suspect you'll end up with other problems because `rush-lib`'s dependency footprint is large and complex. We haven't been able to ship a version of `rush-lib` with all dependencies bundled yet because of these issues. I've been slowly working through them, but it hasn't been trivial.

**Comment by StarFishing** [comment]
The current practice is to deal with rush-lib extenal. If the problem of pnpmfileSettings is solved, there may indeed be other dependency problems. I didn't think of a suitable way now.
we can write it down here and discuss it first.

**Comment by octogonz** [comment]
Here's a proposed solution: https://github.com/microsoft/rushstack/pull/3954

**Comment by NieZhuZhu** [comment]
when I bundle `rush-lib` by esbuild, it succeeded. but when use it, it gets `Cannot find module './commons.js'` error
![image](https://user-images.githubusercontent.com/44939961/230881088-b2a61196-2d94-4bcb-8665-f52dd629a89c.png)
"@microsoft/rush-lib": "^5.97.0", @octogonz
