### ISSUE TITLE
[rush] Installing @latest rush with a downgraded rushVersion specified in rush.json

### ISSUE THREAD

**Issue by Ariit0** [microsoft/rushstack#3979]
## Summary

As of the recent `5.93.0` release I receive the following error when executing rush install after installing the latest rush tooling 

`ERROR: The following environment variables were found with the "RUSH_" prefix,
but they are not recognized by this version of Rush: RUSH_LIB_PATH`

## Repro steps

Install rush@latest and have rushVersion in `rush.json` pointed to any version lower (tested with 5.62.4)

Then run `rush install`

## Standard questions

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.93.0 |
| `rushVersion` from rush.json? | 5.62.4 |
| `useWorkspaces` from rush.json? | true
| Operating system? | Linux |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | 14.20.1|

**Comment by sonnymarton** [comment]
I am seeing the same error with version 5.54.0 as of a few hours ago.

**Comment by octogonz** [comment]
It sounds like a regression from PR #3972.  It seems that the new variable was correctly added to [EnvironmentConfiguration.ts](https://github.com/microsoft/rushstack/blob/e7869e216a887b2b8da94eaddf15903530b6fe1c/libraries/rush-lib/src/api/EnvironmentConfiguration.ts#L450)... but if you are mixing a newer `rush-sdk` with an older `rush-lib` then this is not going to work. 🤔

**Comment by octogonz** [comment]
If we can't fix it quickly, then we may need to temporarily revert this feature.

**Comment by octogonz** [comment]
Here's two fixes for this issue, and I'm proposing to implement both of them:

1. Rename `RUSH_LIB_PATH` to a name without the `RUSH_` prefix so that Rush does complain about it being unsupported. Since it is not intended to be a user-supplied input and more like an internal implementation detail, maybe we can call it `_RUSH_LIB_PATH`.

2. I really like that Rush catches mistakes such as misspelling a variable name or trying to use a variable that is not actually implemented by your Rush version.  However it is pretty disruptive for this to be a hard crash.  We could change it to a yellow warning notice, something like "You defined these RUSH_* variables but they aren't supported by your Rush version" showing the list of variable names.

(1) can be the quick fix.

@dmichon-msft

**Comment by octogonz** [comment]
Elliot's PR: https://github.com/microsoft/rushstack/pull/3980

**Comment by octogonz** [comment]
The fix is publishing now.
