### ISSUE TITLE
[heft] Heft fails with "Resolved configuration object does not match schema" error

### ISSUE THREAD

**Issue by pealmeid** [microsoft/rushstack#4175]
## Summary

Updated my project to the latest versions of heft (`0.51.0`) but it now fails on any heft command with the message `Resolved configuration object does not match schema`. The project builds and runs as expected with heft version `0.50.6`.

## Repro steps
1. Clone the demo repo https://github.com/pealmeid/heft-test;
2. Run `npm install`;
3. Run `heft build`;

  **Expected result:** 
Project should build as expected and `npm run start` should generate `Hello, World!`

  **Actual result:** 
`heft build` fails with the following message:

`Error: Resolved configuration object does not match schema: Error: JSON validation failed:`
`/Projects/heft-test/config/heft.json`
`Error: #/ (Defines configuration used by core Heft.)`
 `Additional properties not allowed: eventActions`

## Details
Project builds and runs as expected if you change `package.json` to use `@rushstack/heft: ^0.50.6`.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@rushstack/heft` version? |  0.51.0|
| Operating system? |Mac OS Ventura and Windows 11|
| Would you consider contributing a PR? | no |
| Node.js version (`node -v`)? | 18.16.0 |

**Comment by octogonz** [comment]
Heft 0.51.0 is a major breaking change - please see these notes:

https://github.com/microsoft/rushstack/blob/main/apps/heft/UPGRADING.md

**Comment by octogonz** [comment]
Btw this week we are working on improving the docs and upgrade guidance.

**Comment by pealmeid** [comment]
> Heft 0.51.0 is a major breaking change - please see these notes:
> 
> https://github.com/microsoft/rushstack/blob/main/apps/heft/UPGRADING.md

Thanks for the quick reply! What is the current guidance on updating? I'm trying to use the new version but I noticed that the validation schema mentioned on the upgrade notes (`https://developer.microsoft.com/json-schemas/heft/heft.schema.json`) does not mention the new properties for `heftPlugins` (e.g. `packageName`, `pluginName` etc.) and, when used with VSCode, warns about some missing (deprecated?) properties (e.g. `plugin`) not mentioned on the upgrade notes:

![heft](https://github.com/microsoft/rushstack/assets/6384219/27160b30-dc34-475e-87d0-d9a29484607d)

We will be staying on version `0.50.6` for now, but I would like to know when can we expect the new documentation/guidance so we can keep our project updated.

Once again, thanks for the quick reply and for an outstanding tool. I'm looking forward to the new version.

**Comment by octogonz** [comment]
>  I would like to know when can we expect the new documentation/guidance so we can keep our project updated.

To fully understand the impact of these changes, I'm personally going through the experience of migrating a couple monorepos to use the new Heft, which should be done by the end of this week. Along the way, we've been fixing various issues to improve the experience, for example:

- https://github.com/microsoft/rushstack/pull/4165
- https://github.com/microsoft/rushstack/pull/4163
- https://github.com/microsoft/rushstack/pull/4170
- https://github.com/microsoft/rushstack/pull/4168

@D4N14L's [UPGRADING.md](https://github.com/microsoft/rushstack/blob/main/apps/heft/UPGRADING.md) doc explains the overall theory of what changed, but I want to add a simpler document that is more like *"If you did ____ before, now you should do ____ instead."*  That should be fairly easy to write up, by looking at diffs from these migrations.

We also need to publish the new `"$schema"` URLs so your VS Code IntelliSense doesn't show those errors. That should get done this week as well.

The next step will be updating the website, which will take a bit longer, since there's a lot of doc pages.  We've been planning to extract the Heft docs from `rushstack.io` into a subsite `heft.rushstack.io`, (like [lfx.rushstack.io](https://lfx.rushstack.io) for Lockfile Explorer), so this might be a good time to introduce that. It might provide a way to keep the old pre-`0.51.0`  docs online for people who haven't upgraded yet.

**Comment by octogonz** [comment]
> **Actual result:** `heft build` fails with the following message:
> 
> ```
> Error: Resolved configuration object does not match schema: Error: JSON validation failed:
> /Projects/heft-test/config/heft.json
> Error: #/ (Defines configuration used by core Heft.)
> Additional properties not allowed: eventActions
> ```

@pealmeid Thanks for reporting this issue BTW!  The above error is not a great user experience.  I've started a conversation about whether Heft can detect an outdated configuration and provide more a understandable notice.

Something like this (hypothetical) output:

```
$ cd my-app
$ heft start

ERROR: This project's Heft config files appear to be using an outdated schema.

Heft 0.51.0 introduced a major breaking change for the Heft config files.
Your project appears to be using the older file format.  You will need
to migrate your project to the new format.  Fortunately, it's fairly easy.

Follow these instructions:  https://rushstack.io/link/heft-0.51
```

**Comment by octogonz** [comment]
> We also need to publish the new `"$schema"` URLs so your VS Code IntelliSense doesn't show those errors. That should get done this week as well.

We can use the `"$schema"`  field to detect outdated config files. So maybe these changes can go together in one PR.

**Comment by octogonz** [comment]
Following up on this: The updated JSON schemas have been published. 

And we have separated the Heft upgrade guidance into two new blog posts:
- [What's New in Heft 0.51](https://rushstack.io/blog/2023/06/15/heft-whats-new/)
- [Heft 0.51 Migration Guide](https://rushstack.io/blog/2023/06/16/heft-migration-guide/)

(By the way we have a Rush Stack blog now! :sunglasses: )
