### ISSUE TITLE
[rush] Need a way to bypass the error raised by #4853

### ISSUE THREAD

**Issue by GongT** [microsoft/rushstack#4967]
## Summary

#4853 

I have used this kind of dependencies for many years in my repo (it's [gongt/baobao](https://github.com/gongt/baobao) but not important). It break my workflow in recent update (rush version 5.131.0 -> 5.132.0)

## Repro steps

  **Expected result:** 
It should be a warning instead of an error. At least it must be configurable somewhere.

  **Actual result:** 
Throw an error and no way to bypass.

## Details

I have at least two scenarios require this. I will try to describe what I'm doing.

> I have two package, Although they list each other in their dependencies, they don't really create any loop. The new check forcing me do an useless (*sometimes impossible*) decouple step.

#### example 1, private dependency loop

No way to bypass, this blocking me from upgrading rush version.

two package: `builder` and `rig`, list each other as dependency. **But they both private**. (extremely easy to decouple since `rig` is just a set of static files, without any build step)

`builder` require files in `rig` to build.    
`rig` require `builder` to "run".

#### example 2, self-bootstrapping

two package: `toolchain` and `library`, both public.

1. `toolchain` runtime requires `library`. can be build with `tsc`
2. `library` build by `ts-node toolchain/bin`

**Comment by GongT** [comment]
Also note (I don't know if it related), `post install` hook still runs even this check fail, this dangerous sometime. *a rm -rf /usr joke*

**Comment by iclanton** [comment]
You can work around this issue by replacing the `workspace:*` dependency with a `link:<relative path to other package folder>`. Note that this is not recommended in Rush and I can't guarantee that this will work in the future.

In your repro repo, it looks like the only project with `decoupledLocalDependencies` listed is your `@internal/local-rig` package. In this repo, we use the published version of `@rushstack/heft-node-rig`, listed in `decoupledLocalDependencies`, to build packages that the local copy of `@rushstack/heft-node-rig` depends on. Your rig package isn't published, but can you build `@build-script/heft-plugin-base`, `@build-script/heft-autoindex-plugin`, `@build-script/heft-typescript-plugin`, and `@build-script/heft-codegen-plugin` with `@rushstack/heft-node-rig` instead to break the cycle?

For your second scenario, I don't see an example of that in your repo. The best approach would probably be to split the `toolchain` package into separate tooling and runtime packages. For the published version, you could have a third package that pulls in output from those two packages.

The scenario you've described feels fairly hacky (i.e. - using `ts-node` to avoid having built `toolchain`). This check exists because the scenario that was previously allowed caused unexpected behavior in the build graph that required unusual workarounds, and that doesn't scale well.

**Comment by GongT** [comment]
Tanks for inspect my repo.

My project is big enough to use something like `rush` to manage them. But it also not so large, a hacky `ts-node` solution is just works.

In the past, I have published a broken version of `toolchain` by mistake, it break everything.      
in another case, I want to upgrade some dependency (eg. `typescript`), but failed: the published `builder` contains some bug, it can not build local `library` with new deps, and then I can't publish a fixed `builder`. finally I must edit .js files in node_modules.

I waste a lot of time on this kind of things, so I invented this hacky way.

**Comment by GongT** [comment]
`ts-node`-like solutions are becoming the "correct" way.

All kinds of TypeScript runners will become less hacky when TypeScript 5.7 is released: [TypeScript 5.7 Beta Announcement](https://devblogs.microsoft.com/typescript/announcing-typescript-5-7-beta/#path-rewriting-for-relative-paths)
The official Node.js runner is also in development: [Node.js TypeScript Support](https://nodejs.org/api/typescript.html)
I need an option to decouple manually. The decoupling logic in Rush is not ideal for enforcing everyone to use it.
