### ISSUE TITLE
[api-documenter] Configure sort order for enum members

### ISSUE THREAD

**Issue by ElizabethSamuel-MSFT** [microsoft/rushstack#918]
It would be great if we could sort the fields in an enum by their value (perhaps with a tag?). For example, we have a bit mask (https://docs.microsoft.com/javascript/api/outlook/office.mailboxenums.delegatepermissions?view=office-js) and it would be more usable if it were sorted by the numeric value instead of the names.

**Comment by pgonzal** [comment]
This seems like a reasonable feature.  However, I wouldn't want it to be the default behavior, since in most cases it seems like alphabetical order would be more useful.

So the first question is how to tell API Extractor to sort the enums by value?

**Comment by AlexJerabek** [comment]
@pgonzal Could it be inferred that if the enum has explicit numerical values, those numbers are important and thus should be the sorting criteria?

Otherwise, a tag seems like a reasonable solution. We could add a `@sortOrder` tag to each enum value defining it's relative order (like `@sortOrder 1`), with the default being the enum's value.

**Comment by ElizabethSamuel-MSFT** [comment]
If we did the "preserveEnumMemberOrder", would that tag the specific enum?

**Comment by pgonzal** [comment]
The basic idea here is that alphabetical order is a pretty sensible default (particularly for code bases that may be somewhat disorganized).  But if you want some other sort order, there maybe isn't always a "natural" ordering.  Consider these examples:

```ts
// Z and MAX_VALUE have the same value.  Should MAX_VALUE come first because it's
// alphabetically earlier?  Or should Z come first since based on the file ordering?
enum Example {
  X = 1,
  Y = 2,
  Z = 3,
  MAX_VALUE = Z
}

// This one uses a bitfield.  Numeric ordering would only be meaningful for the values
// with a single bit.
// https://github.com/Microsoft/web-build-tools/blob/master/libraries/node-core-library/src/PosixModeBits.ts
export enum PosixModeBits {
  UserRead = 1 << 8,
  UserWrite = 1 << 7,
  UserExecute = 1 << 6,
  GroupRead = 1 << 5,
  GroupWrite = 1 << 4,
  GroupExecute = 1 << 3,
  OthersRead = 1 << 2,
  OthersWrite = 1 << 1,
  OthersExecute = 1 << 0,
  None = 0,
  AllRead = OthersRead | GroupRead | UserRead,
  AllWrite = OthersWrite | GroupWrite | UserWrite,
  AllExecute = OthersExecute | GroupExecute | UserExecute
}

// You can also mix together string and number values:
enum Mixed {
  FirstNumber = 123,
  FirstString = '123',
  SecondNumber = 124,
  SecondString = '124'
}
```

So my thinking is that at the point where people care a lot about ordering, maybe it's easier for them to manually order them in the source files.  

> If we did the "preserveEnumMemberOrder", would that tag the specific enum?

I imagined that the personality type who wants this would simply would manage all the enums that way.  They wouldn't need to pick out certain enums that API Extractor should sort.

But I could be wrong about that.  :-)

@ElizabethSamuel-MSFT  Feel free to ping me personally if you want to sort through this a little faster.  :-)

**Comment by AlexJerabek** [comment]
@pgonzal I think you're right that the two options are alphabetical or the order the values appear in the file. Anything more complicated would imply that solution is easier than just sorting your own d.ts.

**Comment by pgonzal** [comment]
Reclassified since this is really a feature request for **api-documenter**, not **api-extractor**.

@AlexJerabek would you be okay with a command-line option such as `api-documenter run --preserve-enum-member-order ...`?  Or do you need to switch it on/off for individual enums?

**Comment by AlexJerabek** [comment]
I think it'd be for individual enums.  Most of the time, we want alphabetical order. The exception is for @ElizabethSamuel-MSFT's bitmask example.

**Comment by pgonzal** [comment]
So then it could be a TSDoc tag like this:

```ts
/**
 * These get sorted alphabetically.
 * @public
 */
export enum Color {
  Red,
  Green,
  Blue
}

/**
 * These do NOT get sorted by the documentation tool.
 * @public @preserveEnumOrder
 */
export enumPosixModeBits {
  UserRead = 1 << 8,
  UserWrite = 1 << 7,
  UserExecute = 1 << 6,
  GroupRead = 1 << 5,
  GroupWrite = 1 << 4,
  GroupExecute = 1 << 3,
  OthersRead = 1 << 2,
  OthersWrite = 1 << 1,
  OthersExecute = 1 << 0,
  None = 0,
  AllRead = OthersRead | GroupRead | UserRead,
  AllWrite = OthersWrite | GroupWrite | UserWrite,
  AllExecute = OthersExecute | GroupExecute | UserExecute
}
```

What do you think?

**Comment by ElizabethSamuel-MSFT** [comment]
@pgonzal I think that could work

**Comment by medabida** [comment]
Hi, Any progress on this?

**Comment by octogonz** [comment]
@medabida It looks like we agreed on a design, so it's just waiting for someone to volunteer to implement it.

I am not able to prioritize this issue right now (my API Extractor time right now would need to go towards getting the backlog of existing PRs merged).  But if someone wants to implement it, there's some basic [docs here](https://api-extractor.com/pages/contributing/building/) and I'm reachable in the [Zulip chat room](https://rushstack.zulipchat.com/) for any questions about the approach.

**Comment by zelliott** [comment]
We'd definitely want to preserve enum member order throughout our entire project. Was the project-wide solution for this to add a new configuration `--preserve-enum-member-order` to API Extractor` Alternatively, what if API Extractor _always_ preserves enum order, but then api-extractor-model is updated to allow for enum members to be returned either in their original order or in alphabetical order?

**Comment by zelliott** [comment]
> I think it'd be for individual enums. Most of the time, we want alphabetical order. The exception is for @ElizabethSamuel-MSFT's bitmask example.

@AlexJerabek: what's an example of an enum that you want alphabetized on your docs site, but not in your source code? This would be somewhat surprising to me.

**Comment by octogonz** [comment]
> what's an example of an enum that you want alphabetized on your docs site, but not in your source code? This would be somewhat surprising to me.

I think the idea is that for a large enum file, it's cumbersome to ask developers to maintain alphabetical order in the source code.  We could introduce an ESLint rule that forces alphabetization, but it might be annoying -- it seems like frivolous human work, given that API Extractor can automatically sort the .d.ts rollup and API docs seen by external consumers. That's the part we really care about.

> Alternatively, what if API Extractor _always_ preserves enum order, but then api-extractor-model is updated to allow for enum members to be returned either in their original order or in alphabetical order?

It also gets sorted in the .d.ts rollup. For people who are being lazy about maintaining their source code, I think they wouldn't want to lose this nice ordering seen by API consumers. (?)

Another consideration:  Every other API item type is alphabetized (`class` members, `namespace` members, etc), so it might be counterintuitive that `enum` should get special treatment.  Despite being counterintuitive, it does make sense: enum members are very small and always in the same source file, so enum order is much easier to maintain manually than other API item types.  This makes me agree that we need this feature, but unsure whether it is the best default.

> Was the project-wide solution for this to add a new configuration `--preserve-enum-member-order` to API Extractor?

Hmm... I think  I disagree with my old self.  😅  This seems better as a setting in `api-extractor.json` (or a TSDoc comment), not the API Documenter CLI. For a given enum, the author of the source code probably knows better than whoever is invoking API Documenter.

A global `api-extractor.json` setting could be like this:

```js
  /**
   * Specifies how API Extractor sorts the members of an enum when generating the .d.ts rollup and
   * .api.json doc model.  The API report is always sorted to avoid spurious diffs.
   *
   * - "by-name": sort the items according to the enum member name
   * - "by-value": sort the items according to the enum value
   * - "preserve": keep the original order that items appear in the source code
   *
   * DEFAULT VALUE: "by-name"
   */
  "enumMemberOrder": "preserve",
```

Additionally, we could have an enum-specific TSDoc override like `{@enumMemberOrder by-value}`. However I wonder how much demand there is. If certain developers feel strongly about ordering of individual enums, perhaps they'll be happy with `"preserve"` in `api-extractor.json` since it gives you full control.

If the `by-value` setting turns out to be nontrivial extra work (e.g. mixtures of strings, numbers, and computed values) we could procrastinate that to a separate PR.

@zelliott what do you think?

**Comment by zelliott** [comment]
Ultimately, the plan to add a new `api-extractor.json` config `"enumMemberOrder"` as you described it sounds good to me. I'd prefer for `"by-value"` to be in a separate PR as I agree there are some open design questions that need to be hammered out. I'd also prefer for the TSDoc `@enumMemberOrder` to be in a separate PR (maybe Microsoft can help contribute some of these requests, if we get the ball rolling with the project-wide config and initial logic within api-extractor). @mrshllstock - does this sound good to you?

---

I'll just leave some quick notes re [what I mentioned in the Zulip chat](https://rushstack.zulipchat.com/#narrow/stream/262521-api-extractor/topic/Adding.20project.20config.20for.20preserving.20Enum.20member.20order/near/283826164). Why alphabetize the `.api.json` in the first place? Why not write _everything_ in the `.api.json` in original source order? This includes members in the entry point, classes, interfaces, enums, etc.

The thinking here is two-fold: (1) the `.api.json` isn't really for human consumption so its sort order shouldn't matter, (2) it's not hard to imagine a team with rigorous code standards wanting to maintain original source order for more than just enums in their generated documentation. In fact, my team is probably on the more-rigorous side of things where we tend to pay very close attention to member order within classes/interfaces/enums/etc. The code is as much documentation as the actual documentation site, if a particular ordering makes sense on the documentation site, it also makes sense in the code. We realize this can sometimes be "cumbersome" for developers, but it's a trade-off we're willing to make for code readability (just as naming variables is cumbersome).

If the documentation site wants to depart from default source code order or a team doesn't have as-strict code standards, then they can tweak their api-documenter to sort things in a specific way. An API could be added to api-extractor-model to return members in one order or another. The point about "the author of the source code probably knows best" makes sense, but I think that should be an argument in favor of a TSDoc tag, not an argument for/against the `.api.json` sort order.

---

That being said - I'm still onboard with the plan as you described it - just wanted to dump my remaining thoughts before closing out the thread. 💭  💭

**Comment by octogonz** [comment]
> Why not write _everything_ in the `.api.json` in original source order? This includes members in the entry point, classes, interfaces, enums, etc.

Actually the entry point doesn't have a well-defined sort order, e.g. `export * from`.  

Alphabetical seems like a reasonable default, since if we look at popular API references (Java, .NET, Ruby, etc) their nav tree is almost always alphabetical. If you know of any counterexamples, it would be interesting to study.

> If the documentation site wants to depart from default source code order or a team doesn't have as-strict code standards, then they can tweak their api-documenter to sort things in a specific way.

We want the .d.ts rollups to be sorted consistently as well, though. Also in general a "team" owns one .api.json file. API Documenter can process many .api.json files collected from different teams/repos with different preferences, so the API Documenter configuration has to be very generic.

In any case, we've outlined a bunch of options -- let's be lazy and solve just the parts that your team will actually use. We can wait for people to request the other designs to judge whether they're worth implementing.

**Comment by zelliott** [comment]
> @octogonz Can we still get the TSDoc tag added for one-off situations?

I don't see why not - and I'd be happy to help review a PR if you have time to open one!
