### ISSUE TITLE
[rush] Common dependency

### ISSUE THREAD

**Issue by ledniy** [microsoft/rushstack#956]
Just started experimenting with rush, is there any way to create common dependency? For example, we using lodash in each project, so I want to save it in "global" package.json or rush.json and then link it to each project.

**Comment by pgonzal** [comment]
@ledniy 

Not today.  Rush assumes that you will probably publish your NPM packages, so all dependencies need to be explicitly specified in each project's **package.json** file.

We do have a plan for Rush eventually to generate **package.json** files during `rush install`, in order to avoid Git merge conflicts that occur when different bots try to bump versions across hundreds of **package.json** files in a monorepo.  (Basically the idea would be to move version numbers into config files corresponding to each bot, and then have a **rush-package.json** that humans edit, and then Rush would combine all this information to make the final **package.json**.  This would also provide a way to scrub/normalize the final package.json used for publishing.)  If we implement this, then it would be straightforward to implement a feature like what you're suggesting.

BTW if you have many projects depending on lodash, Rush does provide a way to keep the versions consistent.  Look for the `ensureConsistentVersions` setting in your **rush.json**.

**Comment by ajmeese7** [comment]
Bump, I would like to see this feature a lot!

**Comment by saul-brightly** [comment]
bump, looking at making a plugin to do the same, having this feature natively would help out greatly!

**Comment by lake2** [comment]
Is this feature avaliable?
